src/views/loaders/withRemoteControl.js, src/views/remote-control.js
Refactor the remote-control view to use the remote control service loader. Built on top of PR #15, so this PR will need rebasing and conflict fixing at some point.
=> ref(remote-control): re-use existing loader

src/features/meeting-frame/meeting-frame.js, src/features/remote-control-menu/remote-control-menu.js, src/remote-control/xmpp.js, src/views/remote-control.js, src/views/view.js
The iframe api has had a notification for screensharing
status change. Use that instead of keeping screensharing
state local to the remote.
=> fix(remote): use screenshare status from api

in-room-controller/src/remote-control.js
So that the ultrasound can start emitting without requiring
to be triggred on a user action.
=> ref(ultrasound): allow media autoplay in web view

spot-client/package-lock.json, spot-client/package.json, spot-client/src/css/code-entry.scss, spot-client/src/css/index.js, spot-client/src/css/temp.scss, spot-client/src/features/code-input/code-input.js, spot-client/src/features/code-input/index.js, spot-client/src/features/nav-button/nav-button.js, spot-client/src/utils/detection.js, spot-client/src/utils/index.js, spot-client/src/views/join-code-entry.js, spot-webdriver/page-objects/join-code-page.js
The current version uses multiple input elements
and switches focus between them. In webviews the
blurring of an input causes the keyboard to be
dismissed and the next input not to be blurred.
The new version uses one input and captures
keyboard events to update the UI to avoid
switching focus on inputs.
=> feat(join-code): custom component for code entry

spot-client/src/features/meeting-frame/meeting-frame.js
If no screenshare connector is setup, wired screensharing
should be disabled. However, disabling screenshare
though the iframe aoi would prevent wireless screensharing
from work. So rely on hiding the screenshare button only
and don't actually disable it.
=> fix(meeting): do not disable screenshare

spot-client/src/app.js, spot-client/src/common/ui/components/error-boundary/error-boundary.js, spot-client/src/common/ui/components/index.js, spot-client/src/common/ui/components/reset/index.js, spot-client/src/common/ui/components/reset/reset.js, spot-client/src/common/ui/views/fatal-error.js, spot-client/src/spot-tv/ui/components/admin/index.js, spot-client/src/spot-tv/ui/views/admin.js
At some point FatalError was changed from a functional
component to a class component. The error boundary
was still expecting a functional component.
While fixint this also brought back the reset state
feature to FatalError and made ErrorBoundary wrap
the entire app.
=> fix(error): use error boundary as class component

spot-client/src/spot-remote/ui/views/join-code-entry.js
join-code is generated on the client, for now, and includes
a case sensitive room lock. While refactoring to allow
the code to be passed a query param, the lowercasing was
lost.
=> fix(join-code): use the lowercase version of the code

spot-client/src/spot-remote/ui/components/remote-control-menu/screenshare-picker.js
There are a lot of unknowns around screensharing UI and UX, one being what icons to show and when to show them. The icons from the designs maybe were not provided (can't tell if they're accessible somewhere but was never told where) so use a couple approximations for now.
=> fix(screenshare): placeholder icons for wired vs wireless

spot-client/package-lock.json, spot-client/package.json, spot-client/src/spot-remote/no-sleep/no-sleep.js, spot-client/src/spot-remote/ui/views/remote-control.js
NoSleep can make Google Chrome Helper user over
100% CPU. A PR is up on the NoSleep repo to use
a longer video file to reduce CPU usage. The
fork drops CPU usage to around 6% whereas without
any NoSleep CPU usage is around 1%.
The exact conditions for when NoSleep should be
triggered is left for consideration but for now
bring back the functionality.
=> fix(remote): bring back sleep prevention

spot-client/package-lock.json, spot-client/package.json, spot-client/src/common/css/code-entry.scss, spot-client/src/common/css/join-code-view.scss, spot-client/src/spot-remote/ui/components/code-input/code-input.js, spot-client/src/spot-remote/ui/components/nav-button/nav-button.js, spot-client/src/spot-remote/ui/views/join-code-entry.js
It was taken out before because iOS webview could
not support changing focus on inputs while keeping
the keyboard displayed. This seems to be fixed
after switching to react-native-webview. So bring
back react-code-input now that is can work in
all necessary environments.
Whether or not we'll keep it long term is another story but the current implementation had to change anyway because it wasn't working on android browsers due to difference in capatibility with onkeypress listening.
=> feat(code-input): bring back react-code-input

spot-client/config.js, spot-client/src/common/remote-control/remote-control-service.js, spot-client/src/common/remote-control/screenshare-connection.js, spot-client/src/index.js
By default lib-jitsi-meet sets the max to 5
unless a value is provided. By default the
max fps will be 60 but it will be configurable
in order to react to perf issues.
=> fix(screenshare): prevent max fps being set to 5

spot-client/src/common/css/home-view.scss, spot-client/src/spot-tv/ui/views/home.js
These changes are temporary. Will wait on design for
final UI/UX, which should include the remote control
url.
=> fix(home): temporarily hide join info footer

spot-client/src/common/reducers/calendars.js, spot-client/src/spot-tv/ui/views/home.js
The edge case is being connected to a calendar with events,
going into setup, changing calendars to one without any
events. No notification of the new events would be sent
out to remotes, leaving them to show events from the
previous calendar. This is because the known events
for the new calendar had not changed (going from empty
to empty) and a calendar fetch had been completed
for the old calendar. The fix is clearing the fetch
flag with the calendar change.
=> fix(calendar): notify remotes of events after calendar change

spot-client/src/common/css/code-entry.scss, spot-client/src/common/css/dial-pad.scss, spot-client/src/common/css/join-code-view.scss, spot-client/src/common/css/meeting-name-entry.scss, spot-client/src/common/css/mixins.scss, spot-client/src/common/css/nav.scss, spot-client/src/common/css/temp.scss
To reduce css duplication, use mixins. The intent
is to use mixins like a toolbox of css without
having to modify the jsx to add classes.
=> ref(css): start using mixins

in-room-controller/ios/mobile.xcodeproj/project.pbxproj
While moving over deps to pod, a build script was removed,
as it was not being included in jitsi-meet's build phases.
Looks like it's needed for building on real devices.
=> fix(ios): re-add a default build script

spot-client/src/common/css/temp.scss, spot-client/src/spot-tv/ui/views/meeting.js
This should hide any flashes of gum permission that
display and any erroneously entered web pages. In
the future it can be used to hide the password prompt.
=> fix(meeting): hide spot-tv's meeting view while it loads

spot-client/src/common/remote-control/xmpp-connection.js
Needed so haproxy knows how to route client
requests to the same shard.
=> fix(xmpp): specify room name for bosh

spot-client/src/common/logger/logger.js, spot-client/src/common/logger/logging-service.js, spot-client/src/common/remote-control/process-update-delegate.js
Objects in logs were being logged as strings,
instead of key-accessible objects. The behavior
was intentional because of how jitsi-meet-logger
concatenates logs as one string, and converting
back to JSON could cause errors. However, this
produces the undesireable log format, so introduce
a context argument object for logging additional
details.
=> fix(logging): prevent double json stringification

spot-client/src/common/debugging/global-debugger.js, spot-client/src/common/debugging/index.js, spot-client/src/common/remote-control/remote-control-service.js, spot-client/src/index.js, spot-client/src/spot-tv/wired-screenshare-service/wired-screenshare-service.js
This way when issues happen the video element used for
detecting can be examined.
=> ref(wired-screenshare): add the detector to the global

spot-client/src/common/remote-control/remote-control-service-subscriber.js, spot-client/src/common/remote-control/remote-control-service.js, spot-client/src/spot-tv/ui/views/home.js
When reconnecting, Spot-TV creates a new XMPP
connection and sets a new join code. The setting
of a join code triggers a redux update, which
updates presence through a redux subscriber.
This ensure the new connection has the updated
presence. Use this mechanism to enusre the
new connection has updated events as well.
Note for the future: probably all notifications for presence should happen through Spot-TV subscriber instead of any component calling directly into remoteControlService to set a status update.
=> fix(reconnect): ensure calendar events are emitted

spot-client/src/common/remote-control/remote-control-service.js, spot-client/src/common/remote-control/screenshare-connection.js, spot-client/src/common/remote-control/xmpp-connection.js
Will pass JitsiConnection to the ProxyConnectionService, so that it can use it to fetch the TURN credentials from Prosody. Those will be used in the P2P screensharing connection.
=> feat: enable TURN

spot-client/config.js, spot-client/package-lock.json, spot-client/package.json, spot-client/src/common/app-state/config/default-config.js, spot-client/src/common/app-state/config/selectors.js, spot-client/src/common/app-state/config/set-default-values.js, spot-client/src/common/app-state/index.js, spot-client/src/index.js, spot-client/webpack.config.js
config used to be part of the main spot-client
app but was moved out for easier overriding
during deployment--better mirroring jitsi-meet's
deployment assumptions. Processing config
through webpack to support dotenv makes the
config output file harder to read. So, convert
config.js to an overrides file and put all
defaults and overrides into spot-client.
=> ref(config): avoid webpack processing

spot-client/src/common/css/temp.scss, spot-client/src/spot-tv/ui/components/setup/index.js, spot-client/src/spot-tv/ui/components/setup/screenshare-input.js, spot-client/src/spot-tv/ui/views/admin.js
Note that there are no UI/UX designs for this section. What's there has been the placeholder designs for over a year now but I still see the admin functionality being useful. The current usage will be for the selenium tests to configure a wired screenshare dongle to get the full screensharing UX.
=> ref(admin): let wired screenshare selection be changeable

package-lock.json
Probably snuck in from an npm install done in
the wrong directory.
=> fix(deps): remove extra package-lock

spot-client/src/spot-remote/ui/components/remote-control-menu/screenshare-picker.js, spot-client/src/spot-tv/ui/components/admin/settings-button.js, spot-webdriver/constants/index.js, spot-webdriver/page-objects/admin-page.js, spot-webdriver/page-objects/calendar-page.js, spot-webdriver/page-objects/remote-control-page.js, spot-webdriver/page-objects/screenshare-picker.js, spot-webdriver/page-objects/spot-remote-in-meeting-page.js, spot-webdriver/specs/helpers/global-after-each.js, spot-webdriver/specs/wireless-screenshare.spec.js, spot-webdriver/user/spot-tv-user.js, spot-webdriver/wdio.conf.js
- Check wireless screensharing can be started in meeting and
out of meeting, both with wired enabled and not enabled.
- Add a global afterEach to clear persisted app state between
tests.
=> feat(tests): basic wireless screensharing flows

spot-client/src/common/app-state/spot-tv/reducer.js, spot-client/src/common/app-state/spot-tv/selectors.js, spot-client/src/spot-remote/ui/components/remote-control-menu/remote-control-menu.js, spot-client/src/spot-remote/ui/components/remote-control-menu/screenshare-picker.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-client/src/spot-remote/ui/views/remote-views/screenshare-modal.js, spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js, spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
There was a transitionary time when jitsi-meet only said
if screensharing was on or off and not the type of screensharing
that is currently enabled. During this time both the boolean
and screenshare type were used to determine the current spot
screenshare status. With the jitsi-meet changes deployed,
just rely on the screenshare type to know screenshare is on.
=> fix(screenshare): stop relying on screensharing boolean

spot-client/src/common/media/av-utils.js, spot-client/src/common/media/index.js, spot-client/src/common/remote-control/screenshare-connection.js, spot-client/src/common/remote-control/xmpp-connection.js, spot-client/src/common/utils/detection.js, spot-client/src/common/vendor/jitsi-meet-js-provider.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js, spot-client/src/spot-tv/ui/components/setup/select-media/camera-preview.js, spot-client/src/spot-tv/ui/components/setup/select-media/mic-preview.js, spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js, spot-client/src/spot-tv/wired-screenshare-service/video-change-listener.js, spot-client/src/spot-tv/wired-screenshare-service/wired-screenshare-service.js
Spot mainly uses lib-jitsi-meet for its MUC handling
and its ProxyPeerConnection. While Spot-TV uses
some of its WebRTC logic, Spot-Remotes does not.
Spot-Remote may be loaded on environments that do
not have full WebRTC support, such as old android
browsers, and preventing app load due to a lack
of WebRTC is unnecessary.
=> fix(vendor): init lib-jitsi-meet only for webrtc calls 

spot-client/src/common/remote-control/remote-control-service.js, spot-client/src/common/remote-control/xmpp-connection.js
Presence updates were throttled in case many calls
to update presence were being made in a short time
span (100ms) to reduce the number of network requests
fired. However, that introduces the 100ms delay,
which adds to the already existing delays of dealing
with prodosy presence updates.
=> fix(xmpp): do not throttle presence updates

spot-client/src/common/css/temp.scss
On safari, the nav icons would not display the circle border
or the label. Somehow the nested flex wrappers and the
flex direction were causing problems. Admittedly the
problem is not understood but removing stylings fixes
it.
=> fix(nav): change flex stylings for safari not rendering

spot-client/src/common/app-state/spot-tv/reducer.js, spot-client/src/spot-tv/ui/components/wired-screenshare/wired-screenshare-detector.js
The edge case is a Spot-TV that has been set up with a screenshare
dongle and goes through setup again without selecting a dongle. In
that case the Spot-Remotes will continue to believe the Spot-TV has
a dongle connected. So instead update state when the dongle is
no longer set.
=> fix(screenshare): notify when screenshare input no longer set

in-room-controller/src/remote-control.js
Scroll needs to be enabled to allow iOS to center
inputs on screen. Zoom has to be enabled to support
iPad Pro centering.
=> fix(remote): allow scroll and zoom for input centering

spot-client/src/common/history/index.js, spot-client/src/index.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-remote/ui/views/share/share.js
This way history can be used outside of components
by being imported as a module.
=> ref(bootstrap): import history

spot-client/src/common/css/mixins.scss, spot-client/src/common/css/page-layouts/spot-tv/meeting-view.scss, spot-client/src/common/css/reset.scss, spot-client/src/common/css/temp.scss
Firefox's min-height 100% is not working like other
browsers.
=> fix(layout): use vh to cover viewport in firefox

spot-client/src/spot-tv/calendars/calendarService.js
This fixes the bug where setup is re-run with the same
calendar selected or a calendar with the same events
selected, and initial event of calendar events having
been fetched doesn't fire because the cached events
is the same.
=> fix(calendar): reset state on re-initialization

spot-client/src/common/css/code-entry.scss
To work around mobile Safari jumping around while
focusing on inputs.
=> fix(join-code): stop using border-box for inputs

spot-client/src/common/css/button.scss
material-ui sets outline to none by default, which
makes it not possible to see when the button is
being focused on when using keyboard navigation.
Example with focus on the second Join Now button:
=> fix(buttons): add focus style

in-room-controller/ios/spot-controller.xcodeproj/project.pbxproj
Set "yes" to "build active architecture only" for debug
This commit also contains other details adjusted by xcode, but they are not related. Pushing them to avoid ping pong.
=> ios: fix build error Library not found for -lDoubleConversion

spot-client/src/common/app-state/remote-control-service/selectors.js, spot-client/src/common/remote-control/remote-control-service.js, spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/ui/loaders/SpotTVRemoteControlLoader.js
Spot-TV setup no longer connects to the remote control
service, so it no longer uses the remote control loader.
This causes the loader component to mount again when
exiting setup, calling connection creation again.
=> fix(rcs): prevent some cases of multiple connection attempts

spot-client/package-lock.json, spot-client/package.json, spot-client/src/spot-tv/calendars/microsoft-client-api/api.js
jsrsasign is used for validating the Outlook
jwt and is used because it is the library
references in the Outlook API docs. The
same functionality can be done with jwt-decode
at a 2kb footprint versus 225kb.
=> ref(deps): replace jsrsasign with jwt-decode

in-room-controller/src/remote-control.js
It was enabled while attempting to fix
the join code page jumping around after
the iOS 12.2 issue. The fix for iOS 12.2
had to do with box-sizing, not zoom.
See commit d3ed9b.
=> fix(in-room-controller): re-disable zoom

spot-client/src/common/ui/components/code-input/code-input.js, spot-client/src/common/ui/components/code-input/input-box.js
Note: this is entirely a workaround and only a partial patch to the UX on android.
=> fix(code-entry): work around android backspace moving focus forward

spot-client/src/common/css/page-layouts/join-code-view.scss
=> ref(code-input): always a 6x1 grid

spot-client/src/common/css/code-entry.scss, spot-client/src/common/ui/components/code-input/code-input.js, spot-client/src/spot-remote/ui/views/join-code-entry.js, spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js
Instead of using 6 input elements, use one, which
will allow backspace to work on Android browser.
=> ref(code-input): rewrite with one input approach

spot-client/src/common/css/temp.scss
=> fix(background): center background image

spot-client/src/app.js, spot-client/src/common/css/help-view.scss, spot-client/src/common/css/index.js, spot-client/src/common/css/page-layouts/join-code-view.scss, spot-client/src/common/icons/index.js, spot-client/src/common/routing/constants.js, spot-client/src/spot-remote/ui/views/help.js, spot-client/src/spot-remote/ui/views/index.js, spot-client/src/spot-remote/ui/views/join-code-entry.js
Clicking on the help icon takes user to the help page.
=> feat: add a help icon to the join code entry page

spot-client/src/spot-remote/ui/views/help.js
The link can be clicked from the iPad app and the user will end up on the unsupported page with no return. Remove the link to remove the problem.
=> ref(help): remove link

spot-client/src/common/css/page-layouts/spot-tv/meeting-view.scss
So that they do not overlap notifications.
=> fix(meeting): center mute icons

spot-client/src/common/css/page-layouts/more-modal.scss, spot-client/src/common/icons/index.js, spot-client/src/spot-remote/ui/components/nav/index.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-client/src/spot-remote/ui/views/remote-views/more-modal.js, spot-webdriver/page-objects/spot-remote-in-meeting-page.js
The tile view button was always meant to be put
into the dumphole that will be the more menu.
Updated the volume button to look like the other
nav button. The previous volume button looked
inconsistent next to the tile view button.
=> feat(nav): move tile view toggle into more menu

spot-client/src/common/app-state/spot-tv/selectors.js, spot-client/src/common/utils/detection.js, spot-client/src/index.js, spot-client/src/spot-remote/ui/loaders/withRemoteControl.js, spot-client/src/spot-remote/ui/views/remote-views/more-modal.js
Re-opening of #309. These changes didn't make it in before volume control so they're being applied after volume control has been merged. The volume control button simply won't display.
We'll need to figure out the UI/UX for this case a big better. But at least for now we're not gonna show the volume buttons when they won't do anything.
=>  feat(detection): add ability to check for volume control support

scripts/ci.sh
There must be a better way...
until that's done, I'm gonna stay dumb. I tried looking up how it would be done in a mono-repo. There could be a root eslint file but I always wanted the root to be pretty clean, with the assumption we'd have non-js projects in here too...and that assumption might just be wrong.
=> fix(ci): lint spot-electron

spot-client/src/app.js, spot-client/src/common/app-state/index.js, spot-client/src/common/app-state/modal/actionTypes.js, spot-client/src/common/app-state/modal/actions.js, spot-client/src/common/app-state/modal/reducer.js, spot-client/src/common/app-state/modal/selectors.js, spot-client/src/common/css/_desktop-picker.scss, spot-client/src/common/ui/components/index.js, spot-client/src/common/ui/components/modal/Modal.js, spot-client/src/common/ui/components/modal/ModalManager.js, spot-client/src/common/ui/components/modal/index.js, spot-client/src/spot-remote/ui/components/electron-desktop-picker/electron-desktop-picker-modal.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-client/src/spot-remote/ui/views/remote-views/more-modal.js, spot-client/src/spot-remote/ui/views/remote-views/screenshare-modal.js
Encapsulate the display and switching of modals
in its own service.
Known todos:
For future PRs:
- Create screenshare and more button components
- Handle escape key, maybe.
- Autofocus keyboard on the modal.
=> feat(modal): add a manager

spot-client/src/spot-remote/ui/components/more/MoreModal.js, spot-webdriver/page-objects/spot-remote-in-meeting-page.js, spot-webdriver/specs/in-meeting.spec.js
Not sure how to test for the existence of volume controls,
which is gated for electron only.
Edit: looked around a bit and there's electron-chromedriver for testing electron apps. Probably that'll need to be done one day to test volume control.
=> feat(tests): add test for checking no volume control on browsers

spot-client/docs/glossary.md, spot-client/src/common/app-state/remote-control-service/actions.js, spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/common/remote-control/constants.js, spot-client/src/common/remote-control/index.js, spot-client/src/common/remote-control/remote-control-service-subscriber.js, spot-client/src/common/remote-control/remoteControlClient.js, spot-client/src/common/remote-control/remoteControlServer.js, spot-client/src/index.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-remote/remote-control/middleware.js, spot-client/src/spot-remote/ui/loaders/withRemoteControl.js, spot-client/src/spot-remote/ui/views/remote-control.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js, spot-client/src/spot-tv/ui/loaders/SpotTVRemoteControlLoader.js, spot-client/src/spot-tv/ui/views/home.js, spot-client/src/spot-tv/ui/views/meeting.js, spot-client/src/spot-tv/ui/views/spot-view.js
This is phase two of a refactor effort to separate spot-remote and spot-tv remote control service logic. Phase 1 was #318, splitting remote control service into two separate objects. Phase 3 will be moving files around.
This PR is built on top of #326, which has some moving of remote control service actions.
=> ref(rcs): rename subclasses to RCServer and RCClient

spot-client/src/index.js
So they can be reported to the logging service.
=> ref(logging): add global uncaught error and rejection logging

spot-client/src/common/css/_screenshare.scss, spot-client/src/spot-remote/ui/components/screenshare/ScreensharePicker.js, spot-client/src/spot-remote/ui/views/share/mode-select.js
Instead of calling it a browser.
=> fix(screenshare): mention device not supported on mobile

spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
Relies on https://github.com/jitsi/jitsi-meet/pull/4289 being deployed. One day these device errors will be reported to a backend so admins know about any device errors the Spot-TV is encountering. For now they get dumped into logs only.
=> feat(meeting): log device errors reported by meeting frame

spot-client/src/common/remote-control/BaseRemoteControlService.js
This type of logic was recently added to ljm to
prevent uncaught exceptions from breaking unload
logic..
=> fix(rcs): capture errors from disconnecting on unload

spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/spot-tv/app-state/actions.js
If a disconnect occurs, or a failed connection occurs,
it was possible to attempt the before the disconnect
logic finished. This could lead to a state where the
remote is connected to the service but the reference
to the xmpp connection was made null. To fix this,
ensure the connection is cleaned up and events of
a disconnect happen after cleanup.
=> fix(reconnect): RCS should clean up own connection on disconnect

spot-client/src/common/css/page-layouts/spot-tv/_setup-view.scss, spot-client/src/spot-tv/calendars/calendarService.js, spot-client/src/spot-tv/calendars/google.js, spot-client/src/spot-tv/ui/components/setup/select-room.js
Google and Outlook truncate room list results to 100. If
a company has more than 100 rooms then not all rooms will
be returned. The Google API allows for querying for rooms,
which provides some search functionality, so that has been
introduced to get around the 100 room limit. Outlook does
not seem to provide such so it's going to have to survive
for a bit in its current state.
Note that this is a partial solution until the real
backend service is complete. Google's API querying matches
to the start of field values only, not in the middle,
and is case sensitive.
=> fix(calendar): allow searching for room in google calendar

spot-client/src/common/utils/window-handler.js, spot-client/src/spot-remote/ui/components/screenshare/ScreensharePicker.js
To make sense on Firefox, Safari, the native mobile apps,
and mobile browsers.
=> fix(screenshare): adjust copy to handle various env cases

spot-client/src/common/app-state/index.js, spot-client/src/spot-tv/native-functions/bt-beacon/index.js, spot-client/src/spot-tv/native-functions/bt-beacon/middleware.js, spot-client/src/spot-tv/native-functions/index.js, spot-electron/.eslintrc, spot-electron/config.js, spot-electron/main.js, spot-electron/package-lock.json, spot-electron/package.json, spot-electron/src/application-window/applicationwindow.js, spot-electron/src/bt-beacon/btbeacon.js, spot-electron/src/bt-beacon/daemon/darwin/bluetoothd.js, spot-electron/src/bt-beacon/daemon/darwin/index.js, spot-electron/src/bt-beacon/daemon/index.js, spot-electron/src/bt-beacon/daemon/win32/index.js, spot-electron/src/bt-beacon/index.js, spot-electron/src/config/config.js, spot-electron/src/utils/index.js, spot-electron/src/utils/stringutils.js
This is the 1st iteration for the soft beacon support for the electron app. This feature starts a soft beacon and starts to emit the join code using the major and minor version of the beacon. The region is fixed, so then we can listen to that explicit region in the mobile app even when the app is not running.
NOTE:
1. The solution only supports mac (mojave) for now, more platforms to coma later.
2. For testing, to resolve the join code from the versions one needs to use this code:
```parseInt((majorInt).toString(16) + (minorInt).toString(16), 16).toString(36)```
This logic will be embedded into the mobile app in iteration 2
=> Soft beacon for electron

spot-client/package.json, spot-client/src/common/emitter/Emitter.js, spot-client/src/common/emitter/index.js, spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/spot-tv/calendars/calendarService.js, spot-client/src/spot-tv/ui/components/setup/select-media/PreviewTrack.js, spot-client/src/spot-tv/wired-screenshare-service/video-change-listener.js
Custom implementation made to avoid the
same callback being registered multiple
times to the same event and to return
an unsubscribe function from addListener.
=> feat: new custom event emitter

spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/common/remote-control/xmpp-connection.js
If backend is in use it will try to use existing lib-jitsi-meet machinery to connect with the JWT to the remote control XMPP server.
=> feat: use JWT to establish XMPP connection with the RCS MUC

spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js, spot-client/src/spot-tv/ui/views/meeting.js
Will use 'jwt' option of the external API to pass a token retrieved from the backend when a meeting is joined by Spot TV.
=> feat: pass JWT to the meeting iframe

spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
Works around an issue where an empty string for
a name will not set a default prop for a display
name to be set in jitsi meet.
=> fix(setup): do not assume default of empty string

spot-client/src/common/css/_modal.scss, spot-client/src/common/css/_screenshare.scss, spot-client/src/common/css/_theme-variables.scss, spot-client/src/common/css/_variables.scss, spot-client/src/common/css/page-layouts/_waiting-view.scss, spot-client/src/spot-remote/ui/components/screenshare/ScreensharePicker.js
I didn't focus much on the narrow width (mobile) stylings. I just made sure they appear. One of the bigger deviations from the designs is not having a separate "modal" for when on an unsupported browser, as calling out "browser" doesn't work out well for the native apps. So instead for unsupported browsers show the wireless screenshare instructions instead of calling out an unsupported nature; this was a bug fix agreed upon several weeks ago with design anyway but I think it was forgotten about during the current screenshare design revisioning.
Mobile ugliness. Narrow width needs work in general. Keep me honest and request any changes you think are necessary now, but we don't have any designs or design attention for most of narrow width.
=> feat(screenshare): new select designs

spot-client/src/spot-tv/calendars/backend-calendar.js
Pass over the fields which could contain a meeting URL.
=> fix(backend-calendar): implement `meetingUrlFields`

spot-client/src/common/remote-control/BaseRemoteControlService.js
=> fix(BaseRemoteControlService): fix crash on undefined `this.options`

spot-client/src/common/css/_temp.scss, spot-client/src/common/css/page-layouts/spot-tv/_meeting-view.scss
Works around an issue currently in beta where
100% height on a child of a parent with 100vh
does not cause the child to also be 100vh.
Also, using vh for the child is more consistent.
=> fix(meeting): make sure meeting fills screen

spot-client/src/common/remote-control/remoteControlClient.js, spot-client/src/spot-remote/ui/views/remote-control.js, spot-client/src/spot-remote/ui/views/share/share.js
In the backend mode there's no need to drop the RCS connection when Spot TV is not in the MUC.
=> ref(Spot Remote/backend): do not disconnect when no Spot TV in MUC

spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js
Do so by removing the  selected camera from the options
for screenshare dongle, but show all available cameras
in the camera dropdown. Also unselect the screenshare
dongle if it matches the selected camera.
=> fix(setup): prevent selecting same camera for screenshare

spot-client/src/common/backend/SpotBackendService.js, spot-client/src/common/backend/constants.js, spot-client/src/common/backend/index.js, spot-client/src/common/backend/utils.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-tv/app-state/actions.js
Otherwise on initial load the connection
creation  will be retried indefinitely.
=> fix(backend): clear pairing code on missing jwt

spot-client/src/spot-tv/app-state/actions.js
Or else the open source flow will have its configured
display name cleared.
=> fix(setup): set display name on backend connection only

spot-client/package.json, spot-client/src/spot-tv/calendars/calendarService.js, spot-client/src/spot-tv/calendars/calendarService.test.js
calendarService should only have one polling process
running at a time, but it could have multiple if
all queued up before the first completed. To prevent
such, use the passed in options to trigger cleanup
of any existing polling process but also check
against the latest polling options to prevent
notifications from old polling processes.
=> fix(calendar): prevent multiple polls from enqueuing

spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
Relies https://github.com/jitsi/jitsi-meet/pull/4466 being merged in and deployed.
=> fix(meeting): prevent deep linking on meeting join

spot-client/src/spot-remote/ui/components/nav/buttons/VideoMuteButton.js, spot-client/src/spot-remote/ui/components/nav/buttons/VideoMuteButton.test.js
This aligns better with jitsi-meet's tooltip for
video muting.
=> fix(button): change video mute button to start/stop camera

spot-client/src/common/css/_code-entry.scss
=> fix(code-input): use scale to hide caret

spot-client/src/common/css/_code-entry.scss
Older browesrs, namely iOS 10 safari, may place the
hidden input to the right of the input boxes instead
of below.
=> fix(code-input): specify left position for older browsers

spot-client/src/common/backend/SpotBackendService.js, spot-client/src/common/backend/index.js, spot-client/src/common/backend/utils.js, spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-tv/app-state/actions.js
- Move isUnrecoverable(Request)Error into the
remote control service to prevent direct
calls into SpotBackendService
- Add checks for not-authorized and password
required when determining if a retry should
occur
If the path of the change looks good, then more testing will have to be doe. Likely some kind of manual test plan will also have to be written and executed to account for the various errors. Unit tests will be coming within the next month.
=> ref(backend): prevent retry loop on some more errors

spot-webdriver/specs/helpers/global-after-each.js, spot-webdriver/wdio.conf.js
Ever since upgrading webdriverio, each spec
file runs in its own browser session. The
global afterEach was running in its own
browser session, not affecting any other
spec file.
=> fix(tests): remove unused global afterEach

spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/common/remote-control/remoteControlClient.js, spot-client/src/common/remote-control/remoteControlServer.js, spot-client/src/common/remote-control/xmpp-connection.js
JitsiConnection#disconnect takes in a browser
event object, which gets passed to its xmpp
connection. If that event is for a beforeunload
or unload event, the the disconnect is fired
synchronously to help ensure it completes.
This should help prevent jid conflicts
while developing and potentially with
upcoming work for selenium tests.
=> fix(rcs): pass onbeforeunload event to xmpp

spot-client/src/common/logger/logger.js
jitsi-meet-logger calls JSON.stringify on
Error instance, but error does not have
enumerable properties so only "{}" gets
logged.
=> fix(logging): stringify error objects manually

spot-client/src/common/css/_code-entry.scss
This reverts commit a96e612c8be1721222ae0cd6704c0d1cd3f685f4.
This breaks iOS auto centering the code input.
=> Revert "fix(code-input): use scale to hide caret"

spot-client/src/common/backend/SpotBackendService.js, spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/common/remote-control/remoteControlServer.js
Fix for infinite loop and adds connection drop on token refresh error.
Will split into two PRs if needed, but the 2nd depends on the 1st being merged to avoid merge conflict, so it's less time this way.
=> Fixes around the backend flow

spot-controller/package-lock.json, spot-controller/package.json, spot-controller/src/remote-control.js
There are no cases for this yet but maybe it's good to
have this included for safety because the webview has
no way to navigate back to the controller page without
refreshing through the settings panel.
=> fix(controller): prevent webview from showing external urls

spot-client/src/common/ui/components/button/button.js, spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js, spot-webdriver/page-objects/admin-page.js
Otherwise when trying to start screenshare only the wireless
screenshare picker will diplay but the tests are waiting
for the wired/wireless picker to display.
=> fix(webdriver): wait for screenshare dongle saving to complete

spot-admin/app.js, spot-client/src/common/css/_code-entry.scss, spot-client/src/common/css/page-layouts/_join-code-view.scss, spot-client/src/common/ui/components/code-input/CodeInput.js, spot-client/src/common/ui/components/code-input/CodeInput.test.js, spot-client/src/spot-remote/ui/views/help.js, spot-client/src/spot-remote/ui/views/join-code-entry.js, spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js, spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.test.js
- If backend flow and app, show 8 boxes
- If backend flow and not the app, show 6 boxes
- If open source flow, always show 6 boxes
Note: this commit re-introduces usage of css-grid
which is not supported in old chrome (polycom).
Android phone open source flow.
Android phone backend flow.
iPad open source flow.
iPad backend flow.
=> feat(join): 8 character code for permanent remote

spot-client/src/common/backend/SpotBackendService.js, spot-client/src/common/backend/SpotBackendService.test.js, spot-client/src/common/backend/constants.js, spot-client/src/common/backend/utils.js, spot-client/src/common/backend/utils.test.js, spot-client/src/spot-tv/backend/SpotTVBackendService.test.js, spot-client/src/spot-tv/backend/SpotTvBackendService.js
Adds a logic which will retry a backend request in case it responds with 401.
Still not sure whether the calendar request should be included or not ?
=> Refresh the access token and retry if backend replies with 401

spot-client/src/common/css/_screenshare.scss, spot-client/src/spot-remote/ui/components/screenshare/ScreensharePicker.js
Missed a spot.
Edit: maybe this means I should make a separate component that's just `<span>{ remoteJoinCode }</span>`.
=> fix(screenshare): use roboto mono for code

spot-client/src/spot-remote/ui/views/join-code-entry.js
Will allow either 6 or 8 characters long pairing codes to be used when entered as part of the URL.
=> feat(join-code-entry): allow either 6 or 8 characters as code from URL

spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/common/remote-control/xmpp-connection.js
Will use 'remote-perm' prefix for a permanent Spot Remote and
'remote-temp' for a temporary one. This will allow the backend to figure
out what's being connected to the MUC.
Example value for a permanent Spot Remote:
'remote-perm-12345678'
Example for a temporary Spot Remote:
'remote-temp-123455678'
The numbers at the end will be 8 random hex characters.
=> feat(RCS): specify MUC JID resource name for Spot Remotes

spot-client/src/common/css/nav/_nav-button.scss
Happens on wide resolutions.
Issue:
With potential fix:
=> fix(nav): prevent overflow cutoff on safari

spot-client/src/common/app-state/device-id/action-types.js, spot-client/src/common/app-state/device-id/actions.js, spot-client/src/common/app-state/device-id/index.js, spot-client/src/common/app-state/device-id/middleware.js, spot-client/src/common/app-state/setup/action-types.js, spot-client/src/common/app-state/setup/actions.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-tv/app-state/actions.js
Will add 'spot-tv', 'remote-perm' or 'remote-temp' as part of the device ID to be able to tell the device type instantly.
=> ref(device-id): include device type in device ID

spot-client/src/common/ui/components/remote-join-code/RemoteJoinCode.js, spot-client/src/spot-tv/ui/components/join-info/join-info.js
Because redux's dispatch is a prop and trying to set
that as an attribute logs an error.
=> ref(join-code): do not spread all props onto join code component

spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js
Adds extra action to be used by the UI in order to establish backend pairing, so that the pairing analytics are not dispatched by the reconnect logic.
=> fix(spot-tv/analytics): do not emit pairing analytics for reconnect

spot-client/webpack.config.js
They are enabled on dev but will now be
enabled for the prod build. Currently a
downside is not seen as the project is
open source already and maps only get
downloaded by dev tools.
=> ref(build): enable source maps by default

spot-client/src/common/css/_desktop-picker.scss, spot-client/src/spot-remote/ui/components/electron-desktop-picker/desktop-picker.js, spot-client/src/spot-remote/ui/components/electron-desktop-picker/electron-desktop-picker-modal.js
I forgot this modal even existed.
=> fix(electron): add skip and submit buttons for desktop picker

spot-controller/src/remote-control.js
Included is an explicit callout to the controller as well as a "feature" version of what the controller supports, which can be used by the controller to do feature compatibility checking if needed.
@paweldomas let me know what you think about this "feature" version part. I was thinking spot-client could use it to check if the spot-controller environment supports some feature and support some kind of legacy behavior (or no-op) if needed. Maybe it's just not needed, plus it's work to manually increment it. At the least I do want this user agent callout.
=> feat(controller): add controller identifier to user agent

spot-client/src/spot-tv/ui/components/setup/PairRemote.js, spot-client/src/spot-tv/ui/views/setup.js
There is no "permanent remote control" for the open source
flows.
=> ref(setup): remove open-source setup flow step of pairing remote

spot-client/src/spot-tv/ui/components/join-info/join-info.js
Saw some logs of someone potentially using the feature, even
though it's for dev only. It's not as useful anymore due to
its lack of support with backend flows.
=> fix(join-code): remove dev feature of clicking code to open remote

spot-client/src/common/analytics/analytics.js, spot-client/src/common/analytics/libs/segment.js, spot-client/src/common/analytics/middleware.js, spot-client/src/common/analytics/segment-handler.js, spot-client/src/common/ui/actionTypes.js, spot-client/src/common/ui/actions.js, spot-client/src/common/ui/index.js, spot-client/src/common/ui/views/view.js
Will log a page event when view is being displayed.
Know issue: all Spot-TV setup steps fall under one page as those are modals displayed on the setup view.
=> feature(analytics): log page event when a View is displayed

spot-webdriver/wdio.conf.js
TimelineService errors if the nested directory
does not exist but can create directories of
one level.
=> fix(webdriver): change results directory

spot-client/src/index.js
Old controllers (app store) are still using this
query param.
=> fix(spot-controller): respect reset query param

spot-client/src/common/css/_modal.scss
View height might get obscured by available height
on iOS safari. As such, drop down to using available
height instead.
I bet this breaks something somewhere.
With fix (notice top-right):
Without fix:
=> fix(modal): take up available height, not view height

spot-client/src/spot-remote/ui/views/join-code-entry.js
Before it was known a mobile application was required,
ultrasound was built to be played from mobile safari,
which requires a user interaction before playing sound.
The workaround was to start playing sound on join code
submit, but that is not needed anymore as the react
native webview can allow sound to play without
interaction.
Probably a larger refactoring of ultrasound is needed to
move away from the "loader" pattern.
=> ref(ultrasound): remove workaround of playing on interaction

spot-client/src/app.js, spot-client/src/common/analytics/middleware.js, spot-client/src/common/app-state/feedback/actionTypes.js, spot-client/src/common/app-state/feedback/actions.js, spot-client/src/common/app-state/feedback/reducer.js, spot-client/src/common/app-state/feedback/selectors.js, spot-client/src/common/app-state/index.js, spot-client/src/common/css/_idle-cursor.scss, spot-client/src/common/css/page-layouts/_feedback-view.scss, spot-client/src/common/css/page-layouts/_join-code-view.scss, spot-client/src/common/icons/index.js, spot-client/src/common/remote-control/remoteControlClient.js, spot-client/src/common/ui/components/feedback/FeedbackForm.js, spot-client/src/common/ui/components/feedback/FeedbackOpener.js, spot-client/src/common/ui/components/feedback/FeedbackOverlay.js, spot-client/src/common/ui/components/feedback/index.js, spot-client/src/common/ui/components/index.js, spot-client/src/spot-remote/analytics/middleware.js, spot-client/src/spot-remote/remote-control/action-types.js, spot-client/src/spot-remote/remote-control/actions.js, spot-client/src/spot-remote/remote-control/middleware.js, spot-client/src/spot-remote/ui/components/remote-control-menu/index.js, spot-client/src/spot-remote/ui/views/join-code-entry.js, spot-client/src/spot-remote/ui/views/remote-views/feedback.js, spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js, spot-client/src/spot-tv/ui/views/home.js
feat(feedback): show feedback button outside of meeting
- Wrap all Spot-Remote route displaying to show the
global feedback button.
- Create a global feedback button for Spot-Remote and
Spot-TV (setup only) to use.
- Move feedback analytics to shared middleware as
now both TV and Remote can send feedback.
- New redux state for controlling app feedback display.
Call feedback display has not been changed.
- Move Feedback components into common and modify
so the star rating can be skipped automatically.
=> feat(feedback): show feedback button outside of meeting

spot-admin/app.js, spot-admin/backend/pair-device.js, spot-admin/backend/refresh-code.js, spot-client/src/common/app-state/config/selectors.js, spot-client/src/common/app-state/setup/action-types.js, spot-client/src/common/app-state/setup/actions.js, spot-client/src/common/app-state/setup/reducer.js, spot-client/src/common/app-state/setup/selectors.js, spot-client/src/common/app-state/spot-tv/selectors.js, spot-client/src/common/backend/SpotBackendService.js, spot-client/src/common/backend/utils.js, spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/common/remote-control/remote-control-service-subscriber.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-remote/app-state/selectors.js, spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js, spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/app-state/index.js, spot-client/src/spot-tv/app-state/selectors.js, spot-client/src/spot-tv/ui/views/meeting.js
If a tenant name is returned with the backend registration then it will be used to construct a URL in an ad-hoc meeting or if the 'location' query parameter is just a meeting name.
=> feat: integrate tenant name if provided by the backend

spot-client/src/common/css/_variables.scss, spot-client/src/common/css/page-layouts/_feedback-view.scss, spot-client/src/common/css/page-layouts/_status-overlay.scss, spot-client/src/common/ui/components/background/Background.js, spot-client/src/common/ui/components/background/index.js, spot-client/src/common/ui/components/index.js, spot-client/src/common/ui/components/status-overlay/StatusOverlay.js, spot-client/src/common/ui/views/fatal-error.js, spot-client/src/common/ui/views/view.js, spot-client/src/spot-remote/ui/components/index.js, spot-client/src/spot-remote/ui/components/waiting-for-spot-tv/WaitingForSpotTVOverlay.js, spot-client/src/spot-remote/ui/components/waiting-for-spot-tv/index.js, spot-client/src/spot-remote/ui/views/remote-control.js, spot-client/src/spot-remote/ui/views/share/share.js
- Use the StatusOverlay styling to make message more visible
- Provide an explicit instructions to check if the Spot-TV
is on
- Adjust z-indexes so feedback icon displays above the new
status overlay
=> feat: display some debugging steps when waiting for spot-tv

spot-client/src/common/app-state/config/default-config.js, spot-client/src/common/app-state/config/selectors.js, spot-client/src/common/app-state/remote-control-service/actions.js, spot-client/src/common/icons/index.js, spot-client/src/common/remote-control/constants.js, spot-client/src/common/remote-control/remoteControlClient.js, spot-client/src/spot-remote/ui/components/dtmf/DTMFButton.js, spot-client/src/spot-remote/ui/components/dtmf/DTMFModal.js, spot-client/src/spot-remote/ui/components/dtmf/index.js, spot-client/src/spot-remote/ui/components/index.js, spot-client/src/spot-remote/ui/components/more/MoreModal.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
- New RCS command for playing touch tones
- New DTMF button for opening the DTMF Modal, which shows a dial pad
~- New StatelessDialPad, which is a copy of DialPad, which does not store internal state of the entered phone number. Used so DTMFModal can clear the entered phone number after submit.~
~- Ended up moving screensharing start functionality into the screensharing button as a result of temporary period where the screensharing button was supposed to be in the More Modal.~
~I'll try to see about splitting out some of these commits. Regardless, these changes cannot be merged until DTMF is fixed on jitsi-meet and the changes have been deployed to all necessary environments.~ Done.
=> feat(dtmf): add dial pad in call

spot-client/src/app.js, spot-client/src/common/routing/constants.js, spot-electron/config.js, spot-webdriver/constants/index.js
To avoid another user-facing reference
to "spot"
spot-electron changes are not backwards compatible but also it's not released.
=> ref(home): create new /tv route

spot-client/src/common/remote-control/XmppConnection.test.js, spot-client/src/common/remote-control/xmpp-connection.js, spot-client/src/spot-remote/app-state/actions.js
Will stringify the entire Spot TV status object into single JSON string and put it in a custom XML element inside MUC presence. The status will come out of XMPPConnection as a ready to use JS object.
=> ref(XmppConnection): send Spot TV presence as single JSON string

spot-client/src/common/remote-control/remoteControlServer.js
There's a message when spot remote leaves, but not when joins. Logging both makes debugging easier.
=> feat: log a message when Spot Remote joins

spot-client/src/spot-remote/app-state/actions.js
New method of serializing tv state to and from JSON does not transport empty or undefined keys. I don't know why exactly, but don't really feel like looking into that. Specify full set of keys on every update by going through the whole list of presence attributes to insert 'undefined' if no value is present.
=> fix(spot tv state): always specify full set of presence key

spot-client/package-lock.json, spot-client/package.json, spot-client/src/spot-remote/ui/components/dial-pad/DialPad.test.js, spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js, spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js, spot-client/src/spot-remote/ui/components/dtmf/DTMFModal.js
Use libphonenumber-js to format the displayed phone number as it's being
typed. Also validates if the phone number is valid, before calling
the onSubmit callback.
Uses 'US' as a default country code for formatting and validation if no
country code is entered manually.
Modifies StatelessDialPad to not pass the value and only call onSubmit
callback when submit action is executed. It is not supposed to track
the state anyway and it is confusing whether to use the value given on
submit or the value that's been submitted last in the on change
callback.
=> feat(dial pad): pretty format and validate phone numbers

spot-client/src/common/css/_dial-pad.scss, spot-client/src/common/css/_mixins.scss, spot-client/src/common/css/page-layouts/_waiting-view.scss, spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js, spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
- Set dimensions to target ipad
- remove RoomName from header to make room
for larger dial pad
- adjust waiting view contents to center of
screen to account for removed padding from
header to make space for dial pad; this
mirrors work-in-progress styles
=> fix(dial): adjust sizing of dial pad

spot-client/src/common/css/_meeting-name-entry.scss
=> fix(adhoc): prevent base url from wrapping

spot-controller/ios/spot-controller/Info.plist
Fixes this error:
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more …
=> ios: add (another) Bluetooth usage purpose to Info.plist

spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js, spot-client/src/spot-remote/ui/utils/formatPhoneNumber.js
It is not recommended by the lib's author to use strict validation as it may easily get outdated and is already missing few numbers we need.
https://github.com/catamphetamine/libphonenumber-js/blob/master/README.md#using-phone-number-validation-feature
=> fix(dial pad): use the least strict validation

spot-client/src/common/remote-control/BaseRemoteControlService.js, spot-client/src/index.js, spot-client/src/spot-remote/app-state/actions.js, spot-client/src/spot-remote/ui/views/remote-control.js, spot-client/src/spot-tv/app-state/actions.js
Moves the before unload handler to index where 'destroyConnection' action can be dispatched before starting the disconnect. This allows to combine 'isConnectionEstablished' selector for the waiting for spot TV message condition(because it clears the connection established state).
=> fix(Spot Remote): waiting for TV to connect appear to often

spot-client/src/common/css/_dial-pad.scss, spot-client/src/common/css/_meeting-name-entry.scss, spot-client/src/common/css/page-layouts/_waiting-view.scss, spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
Stack the domain on top of the input so it does not push the input to be hidden.
Issue:
Proposed fix:
Fix the two issues here of the country picker placeholder being a larger size and the phone icon showing over the picker.
Fix issue with safari where the waiting view contents were getting squashed due to flex properties.
=> UI fixes for dial pad changes and ad-hoc narrow browser

spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-webdriver/page-objects/spot-remote-in-meeting-page.js
A potential source of test failures is the remote
in-meeting page object using the in-call page's
root as an indicator that the page is displayed,
but the page could be displaying a loading icon.
So instead set the root to be the element that
displays after loading has completed.
=> fix(webdriver): remote in-meeting root set to loaded element

spot-client/src/common/backend/utils.js
On 400 status code and if 'pairing.code.not.found' messageKey is present it means that the pairing code is invalid.
=> fix(backend): return NOT_AUTHORIZED in special conditions

spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js
=> ref(SyncWithBackend): display 'Invalid share key' on Spot TV setup

spot-controller/ios/Podfile, spot-controller/ios/Podfile.lock, spot-controller/ios/spot-controller.xcodeproj/project.pbxproj, spot-controller/ios/spot-controller/AppDelegate.m, spot-controller/ios/spot-controller/FIRUtilities.h, spot-controller/ios/spot-controller/FIRUtilities.m
The GoogleService-Info.plist file must be placed in spot-controller/ios dir in order to enable Crashlytics reporting.
=> feat(iOS): add Crashlytics

spot-client/index.html, spot-client/src/app.js, spot-client/src/common/css/_background.scss, spot-client/src/common/css/_code-entry.scss, spot-client/src/common/css/_dial-pad.scss, spot-client/src/common/css/_home-view.scss, spot-client/src/common/css/_meeting-name-entry.scss, spot-client/src/common/css/_meeting.scss, spot-client/src/common/css/_modal.scss, spot-client/src/common/css/_screenshare.scss, spot-client/src/common/css/_temp.scss, spot-client/src/common/css/_theme-variables.scss, spot-client/src/common/css/index.scss, spot-client/src/common/css/page-layouts/_feedback-view.scss, spot-client/src/common/css/page-layouts/_share.scss, spot-client/src/common/css/page-layouts/_status-overlay.scss, spot-client/src/common/css/page-layouts/spot-tv/_admin.scss, spot-client/src/common/css/page-layouts/spot-tv/_setup-view.scss, spot-client/src/common/ui/components/background/Background.js, spot-client/src/common/ui/components/feedback/FeedbackOverlay.js, spot-client/src/common/ui/components/status-overlay/StatusOverlay.js, spot-client/src/common/ui/views/view.js, spot-client/src/spot-remote/ui/components/dtmf/DTMFButton.js, spot-client/src/spot-tv/ui/components/meeting-frame/KickedOverlay.test.js, spot-client/src/spot-tv/ui/views/home.js
Note: per designs there are a lot more gradients applied to the background, which will make other configured backgrounds look kind of dark. If needed, I can add some variables for branding some of these values.
=> Optimize for simpler backgrounds

spot-client/src/common/app-state/config/default-config.js, spot-client/src/common/app-state/config/selectors.js, spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js, spot-client/src/spot-tv/ui/views/meeting.js
As a workaround to prevent voximplaint from
registering two consective same numbers as
being one number.
This is intended to be a temporary workaround.
This limiting should be handled on the ljm
side and voximplant side.
=> fix(meeting): enqueue touch tones

spot-client/src/common/app-state/config/default-config.js
The default time for DTMF tone and pause are 200ms which comes to
the total of 400ms required to finish one sequence. It's been observed
that 3 consecutive tones work better with 500ms than 250ms.
=> chore(config): set DTMF_THROTTLE_RATE to 500ms

spot-client/src/common/css/_modal.scss, spot-client/src/common/css/_screenshare.scss, spot-client/src/common/css/page-layouts/_share.scss, spot-client/src/common/css/page-layouts/_waiting-view.scss, spot-client/src/common/i18n/en.json, spot-client/src/common/ui/components/modal/Modal.js, spot-client/src/spot-remote/ui/components/more/VolumeModal.js, spot-client/src/spot-remote/ui/components/screenshare/ScreenshareModal.js, spot-client/src/spot-remote/ui/components/screenshare/ScreensharePicker.js
=> JIT-3074: new screenshare type picker designs

spot-client/src/common/css/_conference-status-notice.scss, spot-client/src/common/css/index.scss, spot-client/src/common/i18n/en.json, spot-client/src/spot-remote/ui/components/cancel-meeting-prompt/CancelMeetingPrompt.js, spot-client/src/spot-remote/ui/components/cancel-meeting-prompt/index.js, spot-client/src/spot-remote/ui/components/index.js, spot-client/src/spot-remote/ui/components/kicked-notice/KickedNotice.js, spot-client/src/spot-remote/ui/views/remote-views/in-call.js, spot-webdriver/page-objects/spot-remote-in-meeting-page.js, spot-webdriver/specs/adhoc-meeting.spec.js
So if there is a slow join the user can immediately stop the
join.
PR-URL JIT-3413
=> feat(meeting): add a button to cancel a meeting join in progress

spot-electron/entitlements.mac.plist, spot-electron/package-lock.json, spot-electron/package.json, spot-electron/scripts/notarize.js
Adds the post build scrip which executes 'electron-notarize' to notarize the Mac app.
=> feat(electron): notarize Mac app

spot-webdriver/user/spot-user.js
This way there is explicit cleanup of the MUC and the
remote is less likely to encountere race conditions,
like item-not-found errors when trying to connect
to the TV immediately after the TV browser has
navigated away from spot.
=> fix(webdriver): disconnect xmpp before simulating TV close

spot-client/package-lock.json, spot-client/package.json, spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js
Improves country detection by using the parse function which detects country specific syntax. For example 00{country code} or 011{country code} in the US.
=> ref(dial pad): detect the country even if no + was entered

spot-client/src/common/app-state/config/default-config.js, spot-client/src/common/app-state/config/selectors.js, spot-client/src/spot-tv/ui/views/meeting.js
It was used to disable the feature while the prosody
changes weren't vetted or deployed. Now the changes
have been tested and are the norm.
=> ref(config): remove temporary KICK_TEMPORARY_REMOTES flag

spot-integrations-service/README.md, spot-integrations-service/scripts/build.sh
This mirrors the build process for spot-client.
=> feat(integrations): include pushing the image in build script

spot-client/src/app.js, spot-client/src/common/auto-update/AutoUpdateController.js, spot-client/src/common/css/index.scss, spot-client/src/common/css/page-layouts/spot-tv/_conflict.scss, spot-client/src/common/i18n/en.json, spot-client/src/common/remote-control/xmpp-connection.js, spot-client/src/common/routing/constants.js, spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/ui/views/Conflict.js, spot-client/src/spot-tv/ui/views/index.js, spot-webdriver/page-objects/calendar-page.js, spot-webdriver/page-objects/conflict-page.js, spot-webdriver/specs/adhoc-meeting.spec.js, spot-webdriver/specs/share-mode.spec.js, spot-webdriver/specs/spot-tv-conflict.spec.js, spot-webdriver/specs/spot-tv-reconnect.spec.js, spot-webdriver/specs/waiting-for-tv.spec.js, spot-webdriver/user/spot-session.js, spot-webdriver/user/spot-tv-user.js
If Spot TV will fail to join the MUC with conflict error, for longer
than the max client idle timeout, it will mean that most likely another
Spot TV instance is already connected.
The conflict can not be detected instantly, because not gracefully
closed connections are cleaned up only after the idle timeout on
the server.
=> feat: detect Spot TV conflict

spot-client/src/common/i18n/en.json, spot-client/src/spot-remote/ui/components/meeting-name-entry/SelfFillingNameEntry.js, spot-client/src/spot-remote/ui/components/meeting-name-entry/SelfFillingNameEntry.test.js
With tenant, the placeholder says to enter / for a custom tenant.
Without a tenant the placeholder remains the same.
=> fix(adhoc): explain how to enter custom tenant via placeholder

spot-client/src/common/css/page-layouts/spot-tv/_meeting-view.scss, spot-client/src/spot-tv/ui/views/meeting.js
Thereby hiding prompts to get user media.
=> fix(meeting): hide meeting as it loads

spot-client/src/common/zoom/commands.js, spot-client/src/common/zoom/errorCodes.js, spot-client/src/common/zoom/index.js, spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomIframeManager.js, spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomMeetingFrame.js, spot-client/src/zoom/iframe-api/IframeApi.js, spot-client/src/zoom/sdk/controllers/ModalController.js, spot-client/src/zoom/sdk/controllers/index.js, spot-client/src/zoom/sdk/sdk.js
Note that the zoom's modal is being dismissed before any re-join call is made. Currently clicking "OK" dismisses the modal and leaves the page open, which may or may not be intentional on zoom's part. With the modal dismissed, join can be retried without a timeout error occurring.
=> fix(zoom): prompt for password

spot-client/src/common/app-state/config/selectors.js, spot-client/src/common/utils/meeting.js, spot-client/src/common/utils/meeting.test.js, spot-client/src/spot-tv/app-state/actions.js, spot-client/src/spot-tv/ui/components/meeting-frame/MeetingFrame.js
Automagically includes 'zoom.us' domain if zoom is enabled. Check for zoom enabled only on the redirect to meeting action, because it's earlier and seems to be the gate for the TV to join a meeting.
=> ref: auto whitelist zoom domain if enabled

spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomMeetingFrame.js, spot-client/src/zoom/iframe-api/IframeApi.js
If promise is reject it sends back message with an empty 'error' field. Try to store 'message' and 'stack' of an Error and pass it over to the spot parent window to be logged.
=> feat(zoom): pass error to spot-client to be logged

spot-client/src/common/ui/views/fatal-error.js
The View component uses RCS to notify remotes
of the TV's current view. However, if an error
occurred in RCS, it is possible that trying to
use View will cause another error in RCS,
preventing the error boundary from displaying.
Instead, just show the status overlay and
let the TV reconnect.
=> fix(error-boundary): remove View component usage

spot-client/src/common/remote-control/P2PSignalingClient.js, spot-client/src/common/webrtc/PeerConnection.js
If send is called from the RTCDataChannel 'onmessage' event callback,
the channel's ready state or peerconnection's ICE state may not be up
to date and the app may crash while trying to send on closed connection.
Make sendDataChannelMessage return boolean and never throw. Handles
the result only where it matters.
=> fix(p2p): catch RTCDataChannel.send error

spot-client/package-lock.json, spot-client/package.json
Brief history: the queitjs fork currently in
use was supposed to be temporary, but was worked
on with the maintainer of quietjs. Another spot
team member was supposed to work on the "official"
quietjs rewrite but did not deliver so the
temporary fork continued to be used. So for
now, with ultrasound work not close to being
on the radar, the temporary fork has been combined
into jitsi's official quietjs fork.
=> fix(deps): use jitsi fork of quietjs

spot-client/package-lock.json, spot-client/package.json
Logger used to return a json stringified object, but the
latest version includes a timestamp as the beginning. For
now the easiest/safest way to unblock the next release I
see is reverting this update.
=> fix(logging): revert logger update due to invalid json format

spot-electron/entitlements.mac.plist
Try adding 'audio-input' because com.apple.security.device.microphone does not always work.
I don't understand the 'allow-jit' flag, but the internet says it's javascript core related, so better to have it.
=> electron: add audio-input and allow-jit

spot-client/src/common/app-state/spot-tv/reducer.js, spot-client/src/common/app-state/spot-tv/selectors.js, spot-client/src/common/app-state/spot-tv/spotTv.test.js, spot-client/src/common/utils/store-persistence.js, spot-client/src/index.js, spot-client/src/spot-remote/app-state/actions.js
This PR allows the spot tv runtime environment to append a `volumeControlSupported` param to enable the hardware volume control functionality if the runtime environment supports that.
Please note it's rebased on top of https://github.com/jitsi/jitsi-meet-spot/pull/766 so please approve that first
=> Param to enable volume control

spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomIframeManager.js, spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomMeetingFrame.js
Maybe there was a time when the loading had to be
separate from initialization, but not anymore.
=> ref(zoom): always load iframe on IframeManager initialization

spot-client/src/spot-tv/native-functions/native-controller/middleware.js, spot-client/src/spot-tv/native-functions/native-controller/native-controller.js
Turned out that the fact that temp controllers disconnect on leave, makes us unable to use that pairing method for poly remotes. Therefore I added this additional step to signal the long lived pairing code the same way as we signal the temp code, so then the poly remote can use that instead
=> signal llpc through the API

spot-client/src/spot-tv/native-functions/middleware.js, spot-client/src/spot-tv/native-functions/native-commands.js
This PR adds a new native API signal: meeting state.
This is required for the PolyOS api ```CallState```: https://ftp-usa.polycom.com/~betasupport/BETA/G7500/javadoc/index.html?com/poly/polyos/app/CallState.html
=> add meeting state native command

spot-client/src/spot-remote/ui/views/JoinCodeEntry.test.js, spot-client/src/spot-remote/ui/views/join-code-entry.js, spot-controller/src/beacons/middleware.js
This PR makes the controller smarter by only activating beacon detection when the remote is waiting for a join code to be entered (not permanently paired, not in a meeting..etc).
=> feat: don't activate beacons on permanently paired remotes

spot-electron/package.json
Vlad reported that some windows PCs don't have that lib, so we need to include it in the build
=> ref: add new lib for windows

spot-client/src/common/logger/logger.js
- fix issue where context property is split in an array ![Screenshot 2022-11-25 at 4 15 53 PM](https://user-images.githubusercontent.com/686842/204555381-fb958ee6-c3da-480b-af54-f611b4bc8177.png)
=> fix(logging) - fix showing context data when string type

spot-client/src/common/logger/PostToEndpoint/PostToEndpoint.js
- fix parsing log error as now log does not have anymore a JSON structure, for flow when environment config has LOGGING: { ENDPOINT: 'url' } (ex pilot)
- issue introduced in this PR, where structure changed from `object` to beautify `string` (https://github.com/jitsi/jitsi-meet-spot/pull/941/files#diff-6646582b07b7f8b4ebb9b3c29f0b51896877046d210a798c4602fe172d62e23cL15)
Error:
Before:
After:
=> fix(logging) - fix parsing log error for flow with logging endpoint

spot-client/src/spot-remote/ui/components/screenshare/ScreenshareButton.js
- fix share button UI when screensharing is on
- issue introduced from e2e webdriverio changes: 'stop-share' is also used in another place as a container and has flex:1 which increases width of item
=> fix(ui,share-button) - fix share button ui

spot-client/src/common/utils/random.js, spot-client/src/spot-remote/ui/components/meeting-name-entry/SelfFillingNameEntry.js, spot-client/src/spot-remote/ui/components/meeting-name-entry/SelfFillingNameEntry.test.js, spot-client/src/spot-remote/ui/views/join-code-entry.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

spot-client/src/common/media/av-utils.js
Ignore the audio track sicne due to how constraints are handled in LJM we'll always end up getting one.
=> fix(client,wireless-ss) fix sharing Chrome tabs

spot-electron/src/application-window/applicationwindow.js
If we briefly go offline, the meeting will be closed. Instead, ignore offline events while in a meeting, since the network may come back up and the meeting would recover just fine.
=> fix(electron) handle connectivity problems more gracefully

spot-client/src/common/css/_hangup-modal.scss, spot-client/src/common/css/_modal.scss, spot-client/src/common/css/index.scss, spot-client/src/common/i18n/en.json, spot-client/src/spot-remote/ui/components/meeting-toolbar/buttons/HangupButton.js, spot-client/src/spot-remote/ui/components/meeting-toolbar/buttons/HangupModal.js
Add some enhancements to modal (make it can't be clicked through)
Add hang up confirmation.
=> feat(client): improve modal and add hang up confirmation
