- index.html
- src/features/clock/clock.css
- src/features/meeting-name-entry/meeting-name-entry.css
- src/features/remote-control-menu/remote-control-menu.css
- src/features/scheduled-meetings/scheduled-meeting.css
- src/reset.css
- src/utils/background.js
- src/views/loading.js
- src/views/remote-control.js
- src/views/view.css
- src/views/view.js
Use the same background colors and the same font family
declaration and remove the background image. One day
this should easier to configure through admin and css
variables but for now do the easy/quick way.
> fix(styling): change to look more like stride

- src/app.js
- src/config/index.js
- src/features/meeting-frame/meeting-frame.js
- src/features/scheduled-meetings/scheduled-meeting.js
- src/reducers/calendars.js
- src/routing/private-route.js
- src/utils/index.js
- src/utils/meeting.js
- src/utils/url.js
- src/views/calendar.js
- src/views/meeting.js
The app before was configured to always go to one hardcoded
domain. Now allow a list of domains.
> fix(meeting): allow configuring multiple meeting domains

- index.html
- src/features/remote-control-menu/remote-control-menu.js
- src/remote-control/xmpp.js
- src/views/calendar.js
- src/views/loaders/withRemoteControl.js
- src/views/remote-control.js
Make sure the proper room is joined and messages are properly
sent as private.
> fix(xmpp): redo joining logic

- src/features/button/button.js
- src/features/input/input.js
- src/features/meeting-name-entry/meeting-name-entry.js
- src/views/calendar.js
- src/views/view.js
- ui-tests/constants/index.js
- ui-tests/page-objects/calendar-page.js
- ui-tests/page-objects/meeting-input.js
- ui-tests/page-objects/meeting-page.js
- ui-tests/page-objects/page-object.js
- ui-tests/page-objects/remote-control-page.js
- ui-tests/specs/adhoc-meeting.spec.js
- ui-tests/specs/calender.spec.js
- ui-tests/user/user-factory.js
- ui-tests/user/user.js
- ui-tests/wdio.conf.js
This PR is built on top of PR #15, which should go in first and then I'll deal with the conflicts. This PR is for the new webdriver tests for manually entering a meeting name and joining the meeting (last commit).
> feat(tests): acceptance test for entering a meeting name and joining

- src/features/meeting-frame/meeting-frame.js
> fix(meeting): fix detection of meeting failed

- src/app.css
- src/app.js
- src/features/admin/admin.css
- src/features/admin/settings-button.js
- src/features/qr-code/qr-code.js
- src/index.js
- src/views/view.css
Use a global CSS class and CSS declarations
to hide features on idle cursor.
> ref(app): maybe simplify idle cursor handling

- package-lock.json
- package.json
- src/index.js
- src/no-sleep/index.js
- src/no-sleep/no-sleep.js
no sleep is a lib which prevents a phone from
locking automatically due to inactivity by
playing a video in the background.
> feat(remote): prevent phone lock due to inactivity

- docs/wireless_screensharing.md
- index.html
- src/features/meeting-frame/meeting-frame.js
- src/features/remote-control-menu/buttons/wireless-screenshare-button.js
- src/features/remote-control-menu/remote-control-menu.js
- src/reducers/remote-control.js
- src/remote-control/constants.js
- src/remote-control/process-update-delegate.js
- src/remote-control/remote-control-service.js
- src/remote-control/screenshare-connection.js
- src/remote-control/xmpp-connection.js
- src/views/remote-control.js
Relies on https://github.com/jitsi/jitsi-meet/pull/3809 and https://github.com/jitsi/lib-jitsi-meet/pull/857.
> feat(screenshare): support remote wireless screensharing

- spot-client/src/common/logger/post-to-endpoint.js
jitsi-meet-logger de-dupes logs by batching them into
an object with a count. It leaves non-dupe logs as
strings though. By trying to convert the batch to
JSON an error would occur. The chosen fix is to
re-duplicate the logs.
> fix(logging): re-dupe logs

- spot-client/src/common/css/temp.scss
- spot-client/src/spot-remote/ui/loaders/withUltrasound.js
- spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
- spot-client/src/spot-tv/ui/components/join-info/join-info.js
- spot-client/src/spot-tv/ui/views/home.js
- spot-client/src/spot-tv/ui/views/spot-view.js
- Always show remote control url and share key
- Hide placeholder buttons on remote
> fix: style tweaks for demo

- in-room-controller/ios/Podfile
- in-room-controller/ios/mobile.xcodeproj/project.pbxproj
- in-room-controller/package-lock.json
- in-room-controller/package.json
- in-room-controller/src/remote-control.js
- spot-client/src/common/css/code-entry.scss
A react native deprecation warning says to use it.
> fix(mobile): use separate webview package

- in-room-controller/.eslintignore
- in-room-controller/.eslintrc
- in-room-controller/android/app/build.gradle
- in-room-controller/android/app/src/main/java/com/mobile/MainApplication.java
- in-room-controller/android/settings.gradle
- in-room-controller/ios/Podfile
- in-room-controller/ios/Podfile.lock
- in-room-controller/rn-cli.config.js
- scripts/ci.sh
- spot-client/.eslintrc
- spot-webdriver/.eslintignore
- spot-webdriver/page-objects/join-code-page.js
Somehow it worked before, maybe because of local state,
but probably should never have worked.
> fix(controller): redo linking of react-native-webview

- in-room-controller/ios/Podfile.lock
- in-room-controller/package-lock.json
- in-room-controller/package.json
This fixes a random crash by bringing in
react-native pr 22439.
> chore(deps): update to react-native 0.58.5

- spot-client/config.js
- spot-client/src/common/remote-control/xmpp-connection.js
Do not talk to Jicofo when joining the room.
> feat(xmpp-connection): set 'disableFocus' to true

- spot-client/config.js
- spot-client/index.html
- spot-client/webpack.config.js
This will make it easier to override for jitsi-meet's spot-client deployments.
> Nest config in dist/config

- spot-client/Dockerfile
- spot-client/nginx/default.conf
uses a replacement nginx config file
> ensure that content expires from browser cache immediately

- spot-client/src/spot-tv/ui/components/wired-screenshare/wired-screenshare-detector.js
Sometimes the video produced by the USB dongle gets stuck on the last frame when the HDMI cable is disconnected. Redo get user media when the meeting is left to make it produce a black frame again and fix the video change detection.
> fix(wired-screenshare-detector): redo GUM when meeting is left

- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
Relies on https://github.com/jitsi/jitsi-meet/pull/3974. One challenge for the future will be if the Spot-Remote ever has a filmstrip toggle button; there will be questions on how autohiding can live with manual hiding.
> feat(meeting): hide filmstrip when screensharing in lonely call

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/utils/get-random-meeting-name.js
At the least before merging, https://github.com/jitsi/js-utils/pull/7 should be merged first and then this PR updated as needed.
> fix(meet-now): use jitsi-meet's random name logic

- spot-client/src/common/css/clock.scss
- spot-client/src/common/css/code-entry.scss
- spot-client/src/common/css/dial-pad.scss
- spot-client/src/common/css/home-view.scss
- spot-client/src/common/css/join-code-view.scss
- spot-client/src/common/css/meeting-name-entry.scss
- spot-client/src/common/css/meeting.scss
- spot-client/src/common/css/mixins.scss
- spot-client/src/common/css/nav.scss
- spot-client/src/common/css/remote-control-views.scss
- spot-client/src/common/css/screenshare.scss
- spot-client/src/common/css/temp.scss
- spot-client/src/common/css/variables.scss
- spot-client/src/common/ui/components/scheduled-meetings/scheduled-meeting.js
- spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js
In case chrome 30 or chrome 50 needs to be supported.
> Drop grid usage

- spot-client/src/common/app-state/calendars/selectors.js
- spot-client/src/common/app-state/setup/action-types.js
- spot-client/src/common/app-state/setup/actions.js
- spot-client/src/common/app-state/setup/reducer.js
- spot-client/src/common/app-state/setup/selectors.js
- spot-client/src/common/utils/store-persistence.js
- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
- spot-client/src/spot-tv/ui/components/setup/index.js
- spot-client/src/spot-tv/ui/components/setup/profile.js
- spot-client/src/spot-tv/ui/components/setup/select-room.js
- spot-client/src/spot-tv/ui/components/setup/setup.js
- spot-client/src/spot-tv/ui/views/admin.js
- spot-client/src/spot-tv/ui/views/meeting.js
No designs for this yet but add in the hooks for it.
> feat(setup): add way to set custom name and avatar

- spot-client/src/common/remote-control/remote-control-service.js
- spot-client/src/spot-tv/ui/components/wired-screenshare/wired-screenshare-detector.js
- spot-client/src/spot-tv/ui/loaders/SpotTVRemoteControlLoader.js
Update the redux state so the subscriber can update presence.
> Remove remaining direct presence updates

- spot-client/src/common/css/index.js
- spot-client/src/common/css/page-layouts/spot-tv/meeting-view.scss
- spot-client/src/common/css/temp.scss
- spot-client/src/spot-tv/ui/views/meeting.js
This also fixes an issue with the cursor hider causing
scrolling due to block positioning.
> ref(meeting): move spot-tv meeting styles to own file

- spot-admin/app.js
- spot-admin/docs/getting-started.md
- spot-admin/model/SpotRoom.js
- spot-admin/package-lock.json
- spot-admin/package.json
- spot-admin/scripts/get-room-info.sh
- spot-admin/scripts/register-device.sh
- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/app-state/config/selectors.js
- spot-client/src/common/backend/index.js
- spot-client/src/common/backend/utils.js
- spot-client/src/common/logger/post-to-endpoint.js
- spot-client/src/common/remote-control/remote-control-service.js
- spot-client/src/common/remote-control/xmpp-connection.js
- spot-client/src/common/ui/loaders/abstract-loader.js
- spot-client/src/common/utils/device-id.js
- spot-client/src/common/utils/index.js
- spot-client/src/common/utils/retry.js
- spot-client/src/index.js
- spot-client/src/spot-remote/ui/loaders/withRemoteControl.js
- spot-client/src/spot-remote/ui/loaders/withUltrasound.js
- spot-client/src/spot-tv/ui/loaders/SpotTVRemoteControlLoader.js
- spot-client/src/spot-tv/ui/loaders/withCalendar.js
Check `spot-admin/docs/getting-started.md` to see how to use the backend prototype.
It is optional and the app should still be working without it. It doesn't serve any real purpose yet, but adds new flows for getting the join code and MUC room name.
> Adds backend prototype

- spot-client/src/common/css/page-layouts/feedback-view.scss
- spot-client/src/spot-remote/ui/components/remote-control-menu/feedback-form.js
Temporary solution to allow users to skip feedback entry.
> feat(feedback): add skip button

- spot-client/src/common/analytics/events.js
- spot-client/src/common/analytics/index.js
- spot-client/src/common/redux/MiddlewareRegistry.js
- spot-client/src/common/redux/index.js
- spot-client/src/index.js
- spot-client/src/spot-remote/analytics/index.js
- spot-client/src/spot-remote/analytics/middleware.js
- spot-client/src/spot-remote/remote-control/action-types.js
- spot-client/src/spot-remote/remote-control/actions.js
- spot-client/src/spot-remote/remote-control/index.js
- spot-client/src/spot-remote/remote-control/middleware.js
- spot-client/src/spot-remote/ui/components/remote-control-menu/feedback-form.js
- spot-client/src/spot-remote/ui/views/remote-control.js
- spot-client/src/spot-remote/ui/views/remote-views/feedback.js
This commit can probably be split into two parts where one is creating action for submitting the feedback and another one which will add the analytics event.
> Add analytics event for feedback

- spot-client/src/common/css/dial-pad.scss
- spot-client/src/common/css/index.js
- spot-client/src/common/css/input.scss
- spot-client/src/common/css/meeting-name-entry.scss
- spot-client/src/common/css/mixins.scss
- spot-client/src/common/ui/components/input/input.js
- spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js
- spot-client/src/spot-remote/ui/components/meeting-name-entry/meeting-name-entry.js
- spot-client/src/spot-remote/ui/views/join-code-entry.js
- spot-webdriver/page-objects/meeting-input.js
Ignores inputs where temporary styling is used.
> ref: replace inputs with material input

- spot-client/src/common/css/index.js
- spot-client/src/common/css/page-layouts/spot-tv/setup-view.scss
- spot-client/src/common/css/select.scss
- spot-client/src/common/ui/components/index.js
- spot-client/src/common/ui/components/select/index.js
- spot-client/src/common/ui/components/select/simple-select.js
- spot-client/src/spot-tv/ui/components/setup/select-media/media-selector.js
- spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js
This one looks a bit more noticeably different than the other refactors.
> ref: use material-ui select for device selection

- spot-client/src/common/css/index.js
- spot-client/src/common/css/theme-variables.css
- spot-client/src/common/css/variables.scss
scss will otherwise repeatedly import and
declare the variables for each import
statement.
> ref(css): css variables imported only once

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/css/page-layouts/join-code-view.scss
- spot-client/src/common/css/reset.scss
- spot-client/src/common/css/temp.scss
- spot-client/src/spot-remote/ui/components/code-input/code-input.js
- spot-client/src/spot-remote/ui/components/code-input/input-box.js
- spot-client/src/spot-remote/ui/components/nav/nav-button.js
- spot-client/src/spot-remote/ui/views/join-code-entry.js
Will need another PR to continue work for the iOS app (web view). So this work is in progress but this the first chunk of it.
> Fix code input mobile safari

- spot-client/src/common/app-state/setup/selectors.js
- spot-client/src/common/app-state/spot-tv/selectors.js
- spot-client/src/common/css/clock.scss
- spot-client/src/common/css/home-view.scss
- spot-client/src/common/css/mixins.scss
- spot-client/src/common/css/temp.scss
- spot-client/src/common/remote-control/remote-control-service-subscriber.js
- spot-client/src/common/ui/components/index.js
- spot-client/src/common/ui/components/room-name/index.js
- spot-client/src/common/ui/components/room-name/room-name.js
- spot-client/src/spot-remote/ui/loaders/withRemoteControl.js
- spot-client/src/spot-remote/ui/views/remote-views/feedback.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
- spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
- spot-client/src/spot-tv/ui/components/join-info/join-info.js
- spot-client/src/spot-tv/ui/views/home.js
- spot-client/src/spot-tv/ui/views/spot-view.js
Spot-Remote waiting for call:
Spot-Remote in call:
Spot-TV home:
> Display the spot room name

- spot-client/src/app.js
- spot-client/src/common/ui/components/code-input/code-input.js
- spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js
- spot-client/src/spot-tv/ui/views/setup.js
Minor changes before the big ones will come in
> Setup flow fixes

- spot-client/src/common/css/page-layouts/spot-tv/meeting-view.scss
- spot-client/src/spot-tv/ui/components/index.js
- spot-client/src/spot-tv/ui/components/meeting-status/index.js
- spot-client/src/spot-tv/ui/components/meeting-status/meeting-status.js
- spot-client/src/spot-tv/ui/components/meeting-status/status-icon.js
- spot-client/src/spot-tv/ui/views/meeting.js
- spot-webdriver/page-objects/meeting-page.js
- spot-webdriver/specs/in-meeting.spec.js
> feat(meeting): add large audio and video mute icons

- in-room-controller/.eslintignore
- in-room-controller/android/app/BUCK
- in-room-controller/android/app/build.gradle
- in-room-controller/android/app/src/main/AndroidManifest.xml
- in-room-controller/android/app/src/main/java/com/mobile/MainActivity.java
- in-room-controller/android/app/src/main/java/org/jitsi/spot/MainActivity.java
- in-room-controller/android/app/src/main/java/org/jitsi/spot/MainApplication.java
- in-room-controller/android/app/src/main/res/values/strings.xml
- in-room-controller/android/build.gradle
- in-room-controller/android/gradle/wrapper/gradle-wrapper.properties
- in-room-controller/android/settings.gradle
- in-room-controller/metro.config.js
Tried to fix issues by copying parts of the RN 58 template project and searching internets. It appears to be working now.
> android: fix react-native on android

- spot-webdriver/package-lock.json
- spot-webdriver/package.json
- spot-webdriver/screen-info/index.js
- spot-webdriver/wdio.conf.js
screen-info is no longer being maintained and has an outdated
package with a security vulnerability.
> ref(tests): replace screen-info with custom screen count utils

- spot-webdriver/page-objects/join-code-page.js
- spot-webdriver/user/spot-session.js
> fix(tests): update tests for auto-code submission

- in-room-controller/android/app/build.gradle
- in-room-controller/android/app/src/main/java/org/jitsi/spot/MainApplication.java
- in-room-controller/android/settings.gradle
- in-room-controller/ios/Podfile
- in-room-controller/ios/Podfile.lock
- in-room-controller/package-lock.json
- in-room-controller/package.json
- in-room-controller/src/remote-control.js
So a Spot-Remote connected to a Spot-TV won't
go to sleep and lose connectin.
> feat(controller): use react-native-keep-awake

- spot-electron/.eslintignore
- spot-electron/.eslintrc
- spot-electron/config.js
- spot-electron/main.js
- spot-electron/package-lock.json
- spot-electron/package.json
- spot-electron/src/application-menu/applicationmenu.js
- spot-electron/src/application-menu/index.js
- spot-electron/src/application-window/applicationwindow.js
- spot-electron/src/application-window/index.js
- spot-electron/src/config/config.js
- spot-electron/src/config/index.js
- spot-electron/src/logger/index.js
- spot-electron/src/logger/logger.js
Initial commit of the electron app with the loadURL approach as we agreed.
This now supports
- Persistent config
- Window mode changes
- Logging
> Initial commit of spot-electron

- spot-client/webpack.config.js
Binding on all interfaces makes it possible to display the page on LAN
> Bind webpack's dev server to 0.0.0.0

- in-room-controller/src/remote-control.js
- in-room-controller/src/styles.js
Shamefully designed by virtuacoplenny.
> feat(controller): show a placeholder error message when webview fails

- spot-client/src/common/css/page-layouts/spot-tv/setup-view.scss
- spot-client/src/common/css/theme-variables.css
- spot-client/src/spot-tv/ui/components/setup/select-media/camera-preview.js
- spot-client/src/spot-tv/ui/components/setup/select-media/mic-preview.js
- spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js
- spot-client/src/spot-tv/ui/components/setup/select-media/speaker-preview.js
all screenshots are from the admin debug menu.
Video preview disabled:
Speaker preview disabled:
Mic preview disabled
> fix(device-selection): handle unavailable previews

- spot-client/src/common/media/av-utils.js
- spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js
Is there a better way to trigger permissions?
> ref(device-selection): check for perms before forcing requesting

- spot-client/src/spot-tv/ui/components/setup/select-media/select-media.js
I think this finally fixes this edge case.
> fix(wired-ss): update presence on screenshare dongle select

- spot-client/src/spot-remote/ui/components/index.js
- spot-client/src/spot-remote/ui/components/more/MoreButton.js
- spot-client/src/spot-remote/ui/components/more/MoreModal.js
- spot-client/src/spot-remote/ui/components/more/TileViewButton.js
- spot-client/src/spot-remote/ui/components/more/VolumeModal.js
- spot-client/src/spot-remote/ui/components/more/index.js
- spot-client/src/spot-remote/ui/components/nav/buttons/index.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
> ref(more): create standalone more button

- spot-client/src/spot-remote/ui/components/index.js
- spot-client/src/spot-remote/ui/components/remote-control-menu/index.js
- spot-client/src/spot-remote/ui/components/screenshare/ScreenshareButton.js
- spot-client/src/spot-remote/ui/components/screenshare/ScreenshareModal.js
- spot-client/src/spot-remote/ui/components/screenshare/ScreensharePicker.js
- spot-client/src/spot-remote/ui/components/screenshare/index.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
> ref(screenshare): create standalone screenshare button

- spot-client/src/common/remote-control/BaseRemoteControlService.js
- spot-client/src/common/remote-control/remoteControlServer.js
> fix(reconnect): avoid not-authorized error on rejoin

- spot-client/src/common/remote-control/xmpp-connection.js
On xmpp disconnect, strophe does not notify of requests
which have been aborted. To get around this, store the
promise rejections for all IQs and reject them on
disconnect.
> fix(xmpp): ensure pending requests get rejected on disconnect

- spot-client/src/spot-tv/analytics/events.js
- spot-client/src/spot-tv/analytics/index.js
- spot-client/src/spot-tv/analytics/middleware.js
- spot-client/src/spot-tv/app-state/index.js
Will emit events when the pairing fails/succeeds.
Built on top of https://github.com/jitsi/jitsi-meet-spot/pull/359
> Spot TV pairing analytics

- spot-client/src/spot-tv/calendars/google.js
- spot-client/src/spot-tv/calendars/outlook.js
> fix(calendar): hide private details

- spot-controller/App.js
- spot-controller/src/LoadingScreen.js
- spot-controller/src/remote-control.js
third iteration:
second iteration (outdated):
first iteration (outdated):
> feat(webview): cover in loading screen

- spot-client/src/spot-remote/ui/loaders/withRemoteControl.js
- spot-client/src/spot-remote/ui/views/remote-control.js
- spot-client/src/spot-remote/ui/views/share/share.js
Share common logic about unexpected disconnect.
> ref: remove duplication between remote-control and share views

- spot-controller/App.js
- spot-controller/src/settings-menu.js
> feat(controller): provide way to go back to join code

- spot-client/src/common/css/_modal.scss
> fix(modal): make full screen in narrow width

- spot-admin/app.js
- spot-admin/package-lock.json
- spot-admin/package.json
Will automagically try to figure out the room ID if a valid JWT is provided. This makes it easier to test with deployments that have JWT and MUC room validation enabled.
> feat(spot-admin): extract Spot room ID from JWT

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/app-state/spot-tv/selectors.js
- spot-client/src/common/css/_kicked_notice.scss
- spot-client/src/common/css/index.scss
- spot-client/src/spot-remote/app-state/actions.js
- spot-client/src/spot-remote/ui/components/index.js
- spot-client/src/spot-remote/ui/components/kicked-notice/KickedNotice.js
- spot-client/src/spot-remote/ui/components/kicked-notice/index.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
- spot-client/src/spot-tv/ui/components/countdown/Countdown.js
- spot-client/src/spot-tv/ui/components/countdown/Countdown.test.js
- spot-client/src/spot-tv/ui/components/countdown/index.js
- spot-client/src/spot-tv/ui/components/index.js
- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
- spot-client/src/spot-tv/ui/views/meeting.js
Relies on https://github.com/jitsi/jitsi-meet/pull/4390.
Spot-Remote:
Spot-TV:
> feat(in-call): show special UI when kicked

- spot-client/src/spot-tv/ui/components/join-info/join-info.js
- spot-client/src/spot-tv/ui/views/home.js
- spot-client/src/spot-tv/ui/views/spot-view.js
Join code with no setup:
Join code with setup but no share domain configured
Join code with setup and with a share domain configured
> fix(join-info): show url

- spot-client/src/common/css/_home-view.scss
- spot-client/src/spot-tv/ui/views/home.js
with no name set
with name set
> fix(home): show room name below date

- spot-client/src/common/backend/SpotBackendService.js
- spot-client/src/common/backend/utils.js
- spot-client/src/common/remote-control/BaseRemoteControlService.js
@paweldomas, is this too aggressive?
> fix(backend): prevent infinite reconnects when backend errors

- spot-client/src/common/analytics/analytics.js
- spot-client/src/common/analytics/events.js
~Should I do this programmatically somehow?~
> fix(analytics): add prefix

- spot-client/src/common/css/_loading-icon.scss
- spot-client/src/common/css/_temp.scss
- spot-client/src/common/css/index.scss
- spot-client/src/common/css/page-layouts/spot-tv/_setup-view.scss
- spot-client/src/common/ui/components/loading-icon/loading-icon.js
- spot-client/src/common/ui/components/reconnect-overlay/ReconnectOverlay.js
- spot-client/src/common/ui/views/loading.js
- spot-client/src/spot-remote/ui/views/remote-control.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
- spot-client/src/spot-remote/ui/views/share/share.js
- spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js
- spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.test.js
- spot-client/src/spot-tv/ui/views/home.js
> fix(setup): add loading icon while syncing

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/remote-control/xmpp-connection.js
Relies on the outcome of https://github.com/jitsi/lib-jitsi-meet/pull/940. package.json will need updating if https://github.com/jitsi/lib-jitsi-meet/pull/940 is the accepted solution.
> feat(xmpp): set a constant resource on the jid for spot-tvs

- spot-client/src/common/backend/utils.js
Prep-work for all requests having a request-id.
> ref(backend): helper for creating request headers

- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
This way the room name gets piped into callstats
> fix(analytics): enable display name in stats

- spot-controller/ios/spot-controller.xcodeproj/project.pbxproj
I can't get confirmation on what versions to support so I'm picking the one that starts supporting caret-color. I leave it to you to keep me in check.
> fix(controller): stop targeting iOS 10

- spot-client/src/common/remote-control/BaseRemoteControlService.js
- spot-client/src/spot-remote/app-state/actions.js
This will also adjust the logging id based on the room ID.
> feat(spot-remote): dispatch SET_ROOM_ID

- spot-controller/android/app/build.gradle
- add ability to set version from an env variable
- build all architectures
- remove unneeded code from build.gradle
> android: build improvements

- spot-controller/android/app/build.gradle
Fastlane doesn't have a way to do it automagically O_O.
> android: add ability to customize app ID

- spot-client/index.html
- spot-client/src/common/css/_code-entry.scss
- spot-client/src/common/css/_join_info.scss
- spot-client/src/common/css/_mixins.scss
- spot-client/src/common/css/_temp.scss
- spot-client/src/common/css/_theme-variables.scss
- spot-client/src/common/css/index.scss
- spot-client/src/common/css/page-layouts/spot-tv/_admin.scss
- spot-client/src/common/css/page-layouts/spot-tv/_setup-view.scss
- spot-client/src/spot-tv/ui/components/join-info/join-info.js
To reduce confusion between I, L, 0, and 1.
> fix(join): use roboto mono for join code

- spot-controller/.eslintrc
- spot-controller/App.js
- spot-controller/src/remote-control.js
- spot-controller/src/settings-menu/SettingsMenu.js
- spot-controller/src/setup.js
> feat(controller): stop hiding url changing behind dev

- spot-client/src/spot-tv/ui/views/setup.js
> fix: Populate CalendarAuth Config in setup

- README.md
- spot-client/README.md
> Update spot-client readme

- spot-controller/src/setup.js
> feat(controller): use config loading as deployment validation

- spot-client/src/index.js
- spot-controller/App.js
- spot-controller/src/remote-control.js
This is an attempt to simply the reset logic.
The drawback is all local storage gets cleared,
including any data that was external to
the redux state being saved, but maybe that is
for the best.
> ref(controller): inject js to reset app

- spot-client/src/common/app-state/index.js
- spot-client/src/spot-tv/analytics/events.js
- spot-client/src/spot-tv/analytics/middleware.js
Will log 'calendar-error' when calendar events fail to load.
> feature(analytics): log calendar error events

- .gitignore
- spot-webdriver/package-lock.json
- spot-webdriver/package.json
- spot-webdriver/wdio.conf.js
To provide screenshots of the tests.
> feat(webdriver): add timeline reporter

- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
Needs https://github.com/jitsi/jitsi-meet/pull/4573 to work but should cause no errors without it.
> fix(meeting): explicitly send turning screenshare on or off

- spot-admin/app.js
- spot-admin/backend/room-info.js
- spot-client/src/common/analytics/index.js
- spot-client/src/common/analytics/properties.js
- spot-client/src/spot-remote/analytics/middleware.js
- spot-client/src/spot-tv/analytics/middleware.js
Spot room display name now will be set as 'spotRoomDisplayName' analytics property.
> feat(analytics): set display name property

- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/app-state/config/selectors.js
- spot-client/src/spot-remote/ui/components/waiting-for-spot-tv/WaitingForSpotTVOverlay.js
- spot-client/src/spot-remote/ui/views/help.js
- spot-client/src/spot-remote/ui/views/join-code-entry.js
- spot-client/src/spot-tv/ui/components/meeting-frame/FeedbackHider.js
- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
- spot-client/src/spot-tv/ui/components/setup/SyncWithBackend.js
- spot-client/src/spot-tv/ui/views/UnsupportedBrowser.js
- spot-client/src/spot-tv/ui/views/home.js
- spot-controller/src/beacons/middleware.js
- spot-controller/src/settings-menu/SettingsMenu.js
- spot-controller/src/setup.js
I'm unsure how to go about changing the beacon parts. Will sync with Zoli.
> Configurable product name

- spot-client/src/common/app-state/feedback/actions.js
So obvious once pointed out to me.
> fix(feedback): not a skip type if message entered

- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/app-state/config/selectors.js
- spot-client/src/common/remote-control/BaseRemoteControlService.js
- spot-client/src/common/remote-control/P2PSignalingBase.js
- spot-client/src/common/remote-control/P2PSignalingClient.js
- spot-client/src/common/remote-control/P2PSignalingServer.js
- spot-client/src/common/remote-control/constants.js
- spot-client/src/common/remote-control/remoteControlClient.js
- spot-client/src/common/remote-control/remoteControlServer.js
- spot-client/src/common/webrtc/PeerConnection.js
- spot-client/src/common/webrtc/index.js
- spot-client/src/spot-remote/analytics/middleware.js
- spot-client/src/spot-remote/analytics/properties.js
- spot-client/src/spot-remote/app-state/actions.js
- spot-client/src/spot-tv/app-state/actions.js
Opening a draft so we can discuss things here
> Datachannel signaling

- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/common/css/_theme-variables.scss
- spot-client/src/common/css/nav/_nav.scss
- spot-client/src/spot-remote/ui/components/dial-pad/NumberInput.js
- spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
- spot-client/src/spot-remote/ui/components/dtmf/DTMFModal.js
Currently ignoring the DTMF dial pad as
other redesign work continues.
> feat(dial): green call button, custom input

- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/spot-remote/ui/components/dtmf/DTMFModal.js
> fix(dtmf): submit tone on button press

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/common/icons/index.js
- spot-client/src/spot-remote/ui/components/dial-pad/CountryCodePicker.js
- spot-client/src/spot-remote/ui/components/dial-pad/DialPad.test.js
- spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
- spot-client/src/spot-remote/ui/components/dial-pad/countriesInfo.js
- spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js
Cleaned up styles to come in a follow up PR.
> feat(dial): country picker

- spot-client/src/spot-tv/ui/components/setup/select-room.js
I should write unit tests for this but for now this should be enough to unblock.
> fix(setup): properly save custom email address

- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
- spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js
The dial pad will enabled the call button only when a valid phone number has been entered.
> feat(dial pad): dynamically enable/disable the call button

- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/backend/index.js
- spot-client/src/common/backend/utils.js
- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/spot-remote/ui/components/dial-pad/DialPad.test.js
- spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
- spot-client/src/spot-remote/ui/components/dial-pad/dial-pad.js
Will check entered phone number with the phone authorize service before calling a number that could have been blacklisted.
> feat(dial pad): check with the phone authorize service before dialing

- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/spot-remote/ui/components/dial-pad/NumberInput.js
- spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
- spot-client/src/spot-remote/ui/components/dtmf/DTMFModal.js
> fix(dtmf): show entered values

- spot-client/src/common/css/page-layouts/_share.scss
- spot-client/src/common/ui/components/room-name/room-name.js
- spot-client/src/spot-remote/ui/components/index.js
- spot-client/src/spot-remote/ui/components/meeting-header/MeetingHeader.js
- spot-client/src/spot-remote/ui/components/meeting-header/index.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
- spot-client/src/spot-remote/ui/views/share/stop-share.js
> fix(share): show meeting name and url in stop share

- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
> fix(in-call): re-add hangup button listener

- spot-client/src/common/app-state/remote-control-service/actions.js
- spot-client/src/common/app-state/spot-tv/selectors.js
- spot-client/src/common/ui/components/scheduled-meetings/scheduled-meeting.js
- spot-client/src/spot-remote/app-state/actions.js
- spot-client/src/spot-remote/ui/components/meeting-header/MeetingHeader.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
- spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
- spot-client/src/spot-tv/ui/components/meeting-frame/meeting-frame.js
- spot-client/src/spot-tv/ui/views/home.js
- spot-client/src/spot-tv/ui/views/meeting.js
> feat(in-call): show calendar event name if available

- spot-electron/src/application-window/applicationwindow.js
- spot-electron/src/static/crashed.html
> feat(electron): reload window on crash

- spot-client/src/common/css/page-layouts/_feedback-view.scss
- spot-client/src/common/css/page-layouts/_waiting-view.scss
- spot-client/src/spot-remote/ui/views/remote-views/feedback.js
- spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
> clock is part of calendar view only

- spot-client/src/common/css/nav/_nav-button.scss
- spot-client/src/common/i18n/en.json
- spot-client/src/common/icons/index.js
- spot-client/src/spot-remote/ui/components/nav/NavItem.js
- spot-client/src/spot-remote/ui/components/nav/NavList.js
- spot-client/src/spot-remote/ui/components/nav/index.js
- spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
> feat(waiting): new nav design

- spot-client/src/common/css/_meeting-name-entry.scss
- spot-client/src/common/i18n/en.json
- spot-client/src/spot-remote/ui/components/meeting-name-entry/MeetingNameEntry.js
- spot-webdriver/page-objects/meeting-input.js
> feat(adhoc): new name entry design

- spot-client/src/common/css/_dial-pad.scss
- spot-client/src/common/i18n/en.json
- spot-client/src/spot-remote/ui/components/dial-pad/CountryCodeButton.js
- spot-client/src/spot-remote/ui/components/dial-pad/DialPad.test.js
- spot-client/src/spot-remote/ui/components/dial-pad/StatelessDialPad.js
- spot-client/src/spot-remote/ui/components/nav/NavItem.js
> ref(dial): restyle

- spot-client/src/common/css/_meeting-name-entry.scss
- spot-client/src/common/css/nav/_nav-button.scss
- spot-client/src/common/css/page-layouts/_in-call-view.scss
- spot-client/src/common/css/page-layouts/_waiting-view.scss
- spot-client/src/common/i18n/en.json
- spot-client/src/common/icons/index.js
- spot-client/src/spot-remote/ui/components/more/MoreButton.js
- spot-client/src/spot-remote/ui/components/nav/buttons/AudioMuteButton.js
- spot-client/src/spot-remote/ui/components/nav/buttons/AudioMuteButton.test.js
- spot-client/src/spot-remote/ui/components/nav/buttons/VideoMuteButton.js
- spot-client/src/spot-remote/ui/components/nav/buttons/VideoMuteButton.test.js
- spot-client/src/spot-remote/ui/components/nav/nav-button.js
- spot-client/src/spot-remote/ui/components/remote-control-menu/TileViewButton.js
- spot-client/src/spot-remote/ui/components/screenshare/ScreenshareButton.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
> ref(meeting): new button styles

- spot-electron/src/application-menu/applicationmenu.js
- spot-electron/src/application-window/applicationwindow.js
Instead of relying on manual full screen mode.
This will remove the need for saving full screen
preference and window size prefernces.
> ref(electron): use kiosk mode

- spot-client/src/app.js
- spot-client/src/common/css/_electron.scss
- spot-client/src/common/css/_idle-cursor.scss
- spot-client/src/common/css/index.scss
- spot-client/src/common/i18n/en.json
- spot-client/src/common/icons/index.js
- spot-client/src/spot-tv/native-functions/exit/functions.js
- spot-client/src/spot-tv/native-functions/exit/index.js
- spot-client/src/spot-tv/native-functions/index.js
- spot-client/src/spot-tv/ui/components/exit-electron/ExitElectron.js
- spot-client/src/spot-tv/ui/components/exit-electron/ExitVerification.js
- spot-client/src/spot-tv/ui/components/exit-electron/index.js
- spot-client/src/spot-tv/ui/components/index.js
- spot-client/src/spot-tv/ui/index.js
- spot-electron/main.js
- spot-electron/src/application-menu/applicationmenu.js
- spot-electron/src/exit/exitHandler.js
- spot-electron/src/exit/index.js
> feat(electron): exit via spot-tv client only

- spot-client/src/spot-remote/ui/components/meeting-name-entry/MeetingNameEntry.js
- spot-client/src/spot-remote/ui/components/meeting-name-entry/SelfFillingNameEntry.js
- spot-client/src/spot-remote/ui/views/remote-views/waiting-for-call.js
> JIT-3359: skip tenant if entered meeting name starts with slash

- spot-client/src/common/css/page-layouts/_in-call-view.scss
- spot-client/src/common/css/page-layouts/_share.scss
- spot-client/src/spot-remote/ui/components/meeting-header/MeetingHeader.js
- spot-client/src/spot-remote/ui/views/share/share.js
- spot-client/src/spot-remote/ui/views/share/stop-share.js
> fix(share): re-add meeting name to stop share

- spot-electron/src/application-menu/applicationmenu.js
So that windows does not show the menu bar.
> fix(electron): hide menu in prod

- spot-client/src/common/css/_dial-pad.scss
> ref(dial pad): make the plus sign bigger

- spot-client/src/common/app-state/remote-control-service/actions.js
> fix(dial): start with video muted

- spot-client/src/index.js
Now done spot-controller/src/remote-control through injected js
> ref(controller): remove legacy reset code

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/zoom/commands.js
- spot-client/src/spot-tv/ui/components/meeting-frame/ApiHealthCheck/ApiHealthCheck.js
- spot-client/src/spot-tv/ui/components/meeting-frame/ApiHealthCheck/ApiHealthCheck.test.js
- spot-client/src/spot-tv/ui/components/meeting-frame/ApiHealthCheck/index.js
- spot-client/src/spot-tv/ui/components/meeting-frame/JitsiMeetingFrame/JitsiMeetingFrame.js
- spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomIframeManager.js
- spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomMeetingFrame.js
- spot-client/src/zoom/iframe-api/IframeApi.js
Depends on https://github.com/jitsi/js-utils/pull/14 being merged and then package.json in this PR will need to be updated.
> feat(zoom): iframe health check

- spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomMeetingFrame.js
- spot-client/src/spot-tv/ui/views/meeting.js
Display generic failed to join the meeting error for Zoom SDK integration.
> feat(zoom): generic join meeting error

- spot-client/src/common/app-state/spot-tv/reducer.js
- spot-client/src/common/app-state/spot-tv/selectors.js
- spot-client/src/common/app-state/spot-tv/spotTv.test.js
- spot-client/src/common/i18n/en.json
- spot-client/src/spot-remote/app-state/actions.js
- spot-client/src/spot-tv/ui/components/meeting-frame/WaitingForMeetingStartOverlay.js
- spot-client/src/spot-tv/ui/components/meeting-frame/ZoomMeetingFrame/ZoomMeetingFrame.js
- spot-client/src/spot-tv/ui/components/meeting-frame/index.js
- spot-client/src/spot-tv/ui/views/meeting.js
- spot-client/src/zoom/sdk/controllers/ModalController.js
- spot-client/src/zoom/sdk/sdk.js
> fix(zoom): retry to join meeting that has not started

- spot-client/src/common/i18n/en.json
> fix(adhoc): shorten placeholder for custom tenant tip

- spot-integrations-service/README.md
- spot-integrations-service/package-lock.json
- spot-integrations-service/package.json
- spot-integrations-service/src/authentication/ZoomApiSecretRetriever.js
- spot-integrations-service/src/authentication/__tests__/ZoomApiSecretRetriever.test.js
- spot-integrations-service/src/controllers/ZoomSigningController.js
- spot-integrations-service/src/controllers/__tests__/ZoomSigningController.test.js
- spot-integrations-service/src/server.js
The Zoom controller will use the new ZoomApiSecretRetriever
for getting the client secret from AWS. The README and
environment variable checking has been updated to support
environment variables needed to fetch from AWS.
> feat(integrations): fetch zoom secret from secrets manager

- spot-electron/src/application-window/applicationwindow.js
Hiding is extra logic that may not be needed.
> fix(electron): allow window to always show

- spot-client/src/common/utils/store-peristence.test.js
The work on removing the legacy code has been scheduled.
> fix(tests): remove the reminder

- spot-client/src/common/remote-control/xmpp-connection.js
If strophe spams disconnects, onDisconnect
gets called multiple times and reconnects
get piled up. _silentReconnectPromise may
still be undefined so use a new instance
variable for now.
> fix(xmpp): gate reconnects to prevent leaks

- spot-client/src/common/css/_background.scss
- spot-client/src/common/ui/components/background/Background.js
Instead rely on the image itself to have the
styles.
> fix(background): remove styles applied to image

- spot-client/src/common/ui/components/index.js
- spot-client/src/common/ui/components/reset/index.js
- spot-client/src/spot-tv/ui/components/admin/PermanentPairingCode.js
- spot-client/src/spot-tv/ui/components/admin/PermanentPairingCode.test.js
- spot-client/src/spot-tv/ui/components/admin/admin-entry.js
- spot-client/src/spot-tv/ui/components/admin/admin.js
- spot-client/src/spot-tv/ui/components/admin/reset/Reset.js
- spot-client/src/spot-tv/ui/components/admin/reset/ResetConfirmation.js
- spot-client/src/spot-tv/ui/components/admin/reset/index.js
- spot-client/src/spot-tv/ui/components/admin/settings-button.js
This is what hooks usage might look like. I could not use the hook `useEffect` due to the function within `useEffect` not getting called by enzyme and me not finding a suitable workaround; if unit tests were unsupported then this would be okay. As such, I'm not sure we want to adopt it wholesale for spot if that hook cannot be used but this gives us an idea of what usage could look like.
> Introduce react hooks

- scripts/ci.sh
- spot-electron/.eslintrc
- spot-electron/jest.config.js
- spot-electron/package-lock.json
- spot-electron/package.json
- spot-electron/src/application-window/applicationwindow.js
- spot-electron/src/online-detector/OnlineDetector.js
- spot-electron/src/online-detector/OnlineDetector.test.js
- spot-electron/src/online-detector/index.js
- spot-electron/src/static/crashed.html
- spot-electron/src/static/offline.html
- spot-electron/src/static/static.css
> feat(electron): add network offline handling

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/app-state/setup/action-types.js
- spot-client/src/common/app-state/setup/actions.js
- spot-client/src/common/app-state/setup/reducer.js
- spot-client/src/index.js
This is just a refactor to relocate the param persistence to a better place
> relocate start param persistence

- spot-client/docs/manual-test-plan.md
the manual testing doc now contains the details of the new setup flow
> update manual testing doc

- spot-electron/src/bt-beacon/btbeacon.js
This adds a new log into a critical part of the code
> ref: add additional beacon logging

- spot-electron/src/bt-beacon/daemon/win32/bluetoothd.js
The stop function on windows seems to be sync, but the status is not updated immediately, so we need to handle it differently
> fix: timing issue when restarting beacons

- spot-client/package-lock.json
- spot-client/package.json
- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/app-state/config/selectors.js
- spot-client/src/spot-tv/ui/components/meeting-frame/JitsiMeetingFrame/JitsiMeetingFrame.js
- add logic resize filmstrip
- add configuration for resize filmstrip
- remove node-sass and added sass (in order for build to be successful when using node >=14)
- include package-lock
> feat(Filmstrip) add logic resize filmstrip

- spot-electron/main.js
- spot-electron/package-lock.json
- spot-electron/package.json
- update spot electron version to latest
> fix(deps) - update spot electron version

- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/app-state/config/selectors.js
- spot-client/src/spot-tv/ui/views/meeting.js
- disable kick remotes on meeting end
- include configuration value for controlling kick remotes on meetings end
> feat(meeting) - disable kick remotes on meeting end

- spot-client/src/common/logger/PostToEndpoint/PostToEndpoint.js
- on pilot, `text` is not always a JSON
eg: event.text: "2023-01-13T07:53:14.497Z waitingForCall view updating {"activeTab":"input"}"
> fix(log) - fix parsing log when prop text has not json structure

- spot-client/package-lock.json
- spot-client/package.json
- fix left 1 high vulnerability
`(base) ➜  spot-client git:(bduduman/fix_audit_json5) npm audit  
found 0 vulnerabilities`
> fix(npm,audit) - fix audit for json5

- spot-admin/docs/getting-started.md
- spot-admin/package-lock.json
- spot-admin/package.json
- spot-client/config.js
- update packages
- update readme
`
(base) ➜  spot-admin git:(bduduman/spot_admin_updates) npm audit        
found 0 vulnerabilities
(base) ➜  spot-admin git:(bduduman/spot_admin_updates) better-npm-audit audit
🤝  All good!
`
> feat(spot-admin,packages) - update packages to latest

- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/app-state/config/selectors.js
- spot-client/src/spot-remote/ui/views/remote-views/in-call.js
> feat(client) add ability to configure the cancel timeout

- spot-client/src/common/app-state/config/default-config.js
- spot-client/src/common/remote-control/xmpp-connection.js
Make sure we also pass the keep-alive URL if set.
> Fix(client) fix WebSocket connection parameters

- .github/workflows/ci_spot-client.yml
- spot-webdriver/specs/spot-tv-reconnect.spec.js
- spot-webdriver/user/spot-session.js
Wait for the meeting page to be visible before starting to check if the meeting was joined.
> fix(test) fix reconnect test

- spot-client/src/common/app-state/setup/action-types.js
- spot-client/src/common/app-state/setup/actions.js
- spot-client/src/common/app-state/setup/reducer.js
- spot-client/src/common/app-state/setup/selectors.js
- spot-client/src/common/app-state/setup/setup.test.js
- spot-client/src/common/i18n/en.json
- spot-client/src/common/utils/store-persistence.js
- spot-client/src/spot-tv/ui/components/meeting-frame/AbstractMeetingFrame.js
- spot-client/src/spot-tv/ui/components/meeting-frame/JitsiMeetingFrame/JitsiMeetingFrame.js
- spot-client/src/spot-tv/ui/components/setup/profile.js
- spot-client/src/spot-tv/ui/views/meeting.js
The backend generated JWT can include one if desired.
> feat(client) drop ability to specify an avatar URL

- spot-client/src/spot-tv/ui/components/meeting-frame/JitsiMeetingFrame/JitsiMeetingFrame.js
- spot-electron/src/application-window/applicationwindow.js
- **fix(electron) don't override UA string**
- **feat(client) use the "iAmSpot" config option**
- **fix(client) switch to modern config options**
> Improve TV detection by embedded meeting

- spot-client/src/common/css/_modal.scss
Dialogs will have background blur increased and also their background will no longer be transparent allowing for better visibility.
> feat(client): adjust dialog transparency 
